const APP = require('path').join(__dirname, '..', 'app');
const CHROME = process.env.HOMATT_CHROME ||
  require('./chrome').find();
const { chromium } = require('playwright');
const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=APP;
const MIME={'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.db':'application/octet-stream','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.json':'application/json'};
const server=http.createServer((rq,rs)=>{let p=decodeURIComponent(rq.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';fs.readFile(path.join(ROOT,p),(e,d)=>{if(e){rs.writeHead(404);rs.end('nf');return;}rs.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});rs.end(d);});});
const CID='11111111-1111-4111-8111-111111111111',UID='22222222-2222-4222-8222-222222222222';
const SB='https://kgkdiykzmqjougwzzewi.supabase.co';
(async()=>{await new Promise(r=>server.listen(8994,r));
const b=await chromium.launch({executablePath:CHROME,args:['--no-sandbox']});
const page=await(await b.newContext({viewport:{width:430,height:950},deviceScaleFactor:2,hasTouch:true})).newPage();
await page.route('**/*',r=>{const u=r.request().url();
 if(u.startsWith('http://localhost:8994'))return r.continue();
 if(u.startsWith(SB))return r.fulfill({status:200,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:'[]'});
 return r.abort();});
await page.goto('http://localhost:8994/clinic/index.html',{waitUntil:'domcontentloaded'});
await page.evaluate(([cid,uid])=>{localStorage.clear();
 localStorage.setItem('homatt_theme','dark');
 localStorage.setItem('clinic_session',JSON.stringify({staffName:'D',clinicName:'K',clinicId:cid,staffRole:'owner',userId:uid,level:'HC3'}));
 localStorage.setItem('sb-homatt-clinic-auth',JSON.stringify({access_token:'t',refresh_token:'r',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user:{id:uid}}));},[CID,UID]);
await page.goto('http://localhost:8994/clinic/new-order.html',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(2500);
await page.screenshot({path:'screen1.png',fullPage:true});
await page.evaluate(()=>{const el=document.getElementById('confirmedDx');
 el.value='mala'; el.dispatchEvent(new Event('input',{bubbles:true}));});
await page.waitForTimeout(1200);
await page.screenshot({path:'screen1-suggest.png',fullPage:true});
await b.close();server.close();})();
