-- ════════════════════════════════════════════════════════════════════════
--  HOMATT HEALTH — THE DATABASE CHANGES THAT HAVE NOT BEEN APPLIED
--  Generated from supabase/migrations/. Do not edit this file by hand.
-- ════════════════════════════════════════════════════════════════════════
--
--  WHAT THIS IS
--
--  Three features are in the app and their tables are not in the database:
--  the visiting-clinician portal, the owner-only corrections, and the vital
--  flowsheet. Until this runs, those screens will fail — a missing table
--  reaches the phone as an ordinary error, so the app cannot explain itself.
--
--  WHY IT HAS TO BE RUN BY HAND, THIS ONCE
--
--  Migrations are normally applied automatically by the "Apply DB Migrations"
--  GitHub action. It authenticates with SUPABASE_ACCESS_TOKEN, and that token
--  has been REVOKED since about 5 September — every run has returned 401. The
--  same token blocks the Edge Functions. Replacing it is the real fix:
--
--     Supabase dashboard -> Account -> Access Tokens -> generate
--     GitHub -> Settings -> Secrets and variables -> Actions
--             -> SUPABASE_ACCESS_TOKEN -> paste it
--
--  Once that is done everything applies itself again, including this.
--
--  HOW TO RUN IT
--
--     1. Supabase dashboard -> your project -> SQL Editor -> New query
--     2. Paste this whole file
--     3. Run
--     4. It should end with "Success. No rows returned."
--
--  IT IS SAFE TO RUN TWICE. Every statement is `if not exists`,
--  `create or replace` or `drop ... if exists`. Nothing here deletes a
--  patient, a treatment, a sale or a shilling. Running it again changes
--  nothing — that is checked by applying it twice to a real Postgres on every
--  test run.
--
--  IT IS ALL OR NOTHING. The SQL Editor runs a pasted script as ONE
--  transaction, so if any line fails, everything rolls back and the database
--  is exactly as it was. There is no half-applied state to clean up.
--
--  WHAT IT CHANGES THAT ALREADY EXISTS
--
--    get_clinic_stock   gains a check that the CALLER belongs to the clinic.
--                       It previously handed any signed-in Homatt user any
--                       clinic's shelves. All thirteen of its columns —
--                       including expiry_date, is_expired and
--                       is_expiring_soon — are kept exactly as they are, so
--                       the stock screen's expiry warnings are untouched.
--    adjust_inventory   the same caller check.
--    deduct_inventory   the same caller check.
--
--  Nothing else that exists is replaced.
--
--  CONTENTS
--
--    1. 20260911_clinician_portal.sql      The visiting-clinician portal — sign up, QR handshake, work history
--    2. 20260912_owner_corrections.sql     Owner-only corrections, and the inventory hole it closes
--    3. 20260916_vital_flowsheet.sql       The vital flowsheet — readings, notes and monitoring orders
--
-- ════════════════════════════════════════════════════════════════════════



-- ╔══════════════════════════════════════════════════════════════════════
-- ║  PART 1 of 3 — The visiting-clinician portal — sign up, QR handshake, work history
-- ║  source: supabase/migrations/20260911_clinician_portal.sql
-- ╚══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════
-- Homatt Health — the CLINICIAN portal
--
-- A clinician is a person, not a seat at one clinic. They sign up once,
-- carry their own profile and their own work record, and attach
-- TEMPORARILY to a clinic by scanning that clinic's QR code. When the
-- attachment ends the record stays with them and goes to the next
-- clinic; the patients do not.
--
-- ── THE ONE RULE THIS FILE EXISTS TO ENFORCE ──────────────────────
-- PATIENT IDENTITY NEVER TRAVELS WITH THE CLINICIAN.
-- clinician_activity — the table that follows a clinician from clinic
-- to clinic — has NO patient name, NO phone, NO patient id, and no
-- column that could carry one. It records that a condition was treated,
-- at which clinic, on which day. That is a professional record. A list
-- of the people someone treated is a medical record, and it belongs to
-- the clinic that made it.
--
-- This is structural, not a policy: there is no column to leak. A
-- future change that adds one is the change to stop in review.
--
-- Tables
--   clinicians           the standalone professional identity
--   clinic_link_codes    the QR handshake — short-lived, revocable
--   clinic_clinicians    one attachment (a stint) of a clinician to a clinic
--   clinician_activity   automatic, patient-free log of work done
--   clinician_ratings    what an owner says when somebody leaves
--
-- Idempotent — safe to run more than once.
-- ════════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto with schema extensions;

-- ── 1. The clinician ────────────────────────────────────────────────
create table if not exists public.clinicians (
  id                uuid primary key default gen_random_uuid(),
  auth_user_id      uuid unique references auth.users(id) on delete cascade,
  full_name         text not null,
  profession        text,          -- Doctor / Clinical Officer / Nurse / Midwife / Lab
  cadre             text,          -- Medical Officer, Senior CO, Enrolled Nurse …
  registration_no   text,          -- UMDPC / UNMC / AHPC number
  registration_body text,
  qualification     text,          -- MBChB, Dip CM, BScN …
  years_experience  integer,
  phone             text,
  email             text,
  district          text,          -- where they stay
  sub_county        text,
  village           text,
  address           text,
  languages         text,
  bio               text,
  photo_url         text,
  is_active         boolean default true,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create index if not exists clinicians_auth_idx on public.clinicians(auth_user_id);
create index if not exists clinicians_reg_idx  on public.clinicians(lower(registration_no));

comment on table public.clinicians is
  'A clinician''s own account. Independent of any clinic — it outlives every attachment.';

-- ── 2. The handshake code a clinic shows as a QR ────────────────────
create table if not exists public.clinic_link_codes (
  id           uuid primary key default gen_random_uuid(),
  clinic_id    uuid not null references public.clinics(id) on delete cascade,
  code         text not null unique,
  created_by   uuid,                       -- auth.users id of the owner
  role         text default 'visiting_clinician',
  access_days  integer default 30,         -- how long the access it grants lasts
  expires_at   timestamptz not null,       -- how long the CODE itself is good for
  max_uses     integer default 1,
  uses         integer default 0,
  revoked      boolean default false,
  created_at   timestamptz default now()
);

create index if not exists clinic_link_codes_clinic_idx on public.clinic_link_codes(clinic_id);
create index if not exists clinic_link_codes_code_idx   on public.clinic_link_codes(upper(code));

comment on table public.clinic_link_codes is
  'Short-lived codes a clinic shows as a QR. Scanning one attaches a clinician temporarily.';

-- ── 3. The attachment — one stint at one clinic ─────────────────────
create table if not exists public.clinic_clinicians (
  id            uuid primary key default gen_random_uuid(),
  clinic_id     uuid not null references public.clinics(id) on delete cascade,
  clinician_id  uuid not null references public.clinicians(id) on delete cascade,
  auth_user_id  uuid,                      -- denormalised: RLS reads it without a join
  status        text default 'active' check (status in ('active','ended','revoked','expired')),
  role          text default 'visiting_clinician',
  started_at    timestamptz default now(),
  expires_at    timestamptz,               -- TEMPORARY by default
  ended_at      timestamptz,
  ended_by      text check (ended_by in ('owner','clinician','expired','system')),
  end_reason    text,
  joined_via    text default 'qr',         -- 'qr' | 'code'
  link_code_id  uuid references public.clinic_link_codes(id) on delete set null,
  created_at    timestamptz default now()
);

create index if not exists clinic_clinicians_clinic_idx    on public.clinic_clinicians(clinic_id);
create index if not exists clinic_clinicians_clinician_idx on public.clinic_clinicians(clinician_id);
create index if not exists clinic_clinicians_auth_idx      on public.clinic_clinicians(auth_user_id);

comment on table public.clinic_clinicians is
  'One period of work by one clinician at one clinic. Temporary and revocable.';

-- ── 4. The work record that travels ─────────────────────────────────
-- Read the header of this file before adding a column here.
create table if not exists public.clinician_activity (
  id            uuid primary key default gen_random_uuid(),
  clinician_id  uuid not null references public.clinicians(id) on delete cascade,
  clinic_id     uuid references public.clinics(id) on delete set null,
  stint_id      uuid references public.clinic_clinicians(id) on delete set null,
  kind          text default 'treatment',
  condition     text,            -- WHAT was treated. Never WHO.
  severity      text,
  occurred_at   timestamptz default now(),
  created_at    timestamptz default now()
);

create index if not exists clinician_activity_clinician_idx on public.clinician_activity(clinician_id, occurred_at desc);
create index if not exists clinician_activity_clinic_idx    on public.clinician_activity(clinic_id, occurred_at desc);

comment on table public.clinician_activity is
  'Patient-free professional log. Deliberately has no column that can hold a patient identity.';
comment on column public.clinician_activity.condition is
  'The condition treated — never the person treated.';

-- ── 5. What an owner says when somebody leaves ──────────────────────
create table if not exists public.clinician_ratings (
  id             uuid primary key default gen_random_uuid(),
  clinic_id      uuid not null references public.clinics(id) on delete cascade,
  clinician_id   uuid not null references public.clinicians(id) on delete cascade,
  stint_id       uuid references public.clinic_clinicians(id) on delete set null,
  rated_by       uuid,
  rater_name     text,
  rating         integer check (rating between 1 and 5),
  care           integer check (care between 1 and 5),
  punctuality    integer check (punctuality between 1 and 5),
  record_keeping integer check (record_keeping between 1 and 5),
  teamwork       integer check (teamwork between 1 and 5),
  would_rehire   boolean,
  reference_note text,
  created_at     timestamptz default now(),
  unique (stint_id)
);

create index if not exists clinician_ratings_clinician_idx on public.clinician_ratings(clinician_id);

comment on table public.clinician_ratings is
  'An owner''s reference for a clinician who worked at their clinic. Travels with the clinician.';

-- ════════════════════════════════════════════════════════════════════
-- Row level security
--
-- These five tables are written tight, and deliberately so. The older
-- tables in this database carry permissive `using (true)` policies from
-- an earlier stage of the project; nothing here relies on them.
-- ════════════════════════════════════════════════════════════════════

alter table public.clinicians         enable row level security;
alter table public.clinic_link_codes  enable row level security;
alter table public.clinic_clinicians  enable row level security;
alter table public.clinician_activity enable row level security;
alter table public.clinician_ratings  enable row level security;

-- Is the caller an active owner of this clinic?
create or replace function public.is_clinic_owner(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portal_users pu
     where pu.auth_user_id = auth.uid()
       and pu.clinic_id    = p_clinic_id
       and pu.is_active    = true
       and coalesce(pu.staff_role, 'owner') = 'owner'
  );
$$;
grant execute on function public.is_clinic_owner(uuid) to authenticated;

-- The caller's own clinician row id, if they have one.
create or replace function public.my_clinician_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select c.id from public.clinicians c where c.auth_user_id = auth.uid() limit 1;
$$;
grant execute on function public.my_clinician_id() to authenticated;

-- ── clinicians ──
-- A clinician reads and writes their own row. A clinic owner may read the
-- row of anybody who is, or has been, attached to their clinic — that is
-- how they see who they are letting in, and how a reference is checked.
drop policy if exists "clinician reads own record"      on public.clinicians;
drop policy if exists "clinician writes own record"     on public.clinicians;
drop policy if exists "clinician creates own record"    on public.clinicians;
drop policy if exists "owner reads attached clinicians" on public.clinicians;

create policy "clinician creates own record" on public.clinicians
  for insert to authenticated with check (auth_user_id = auth.uid());
create policy "clinician reads own record" on public.clinicians
  for select to authenticated using (auth_user_id = auth.uid());
create policy "clinician writes own record" on public.clinicians
  for update to authenticated using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());
create policy "owner reads attached clinicians" on public.clinicians
  for select to authenticated using (
    exists (
      select 1 from public.clinic_clinicians cc
       where cc.clinician_id = clinicians.id
         and public.is_clinic_owner(cc.clinic_id)
    )
  );

-- ── clinic_link_codes ── owners only. A clinician never reads the table;
-- they redeem a code through an RPC, which is why a stolen code alone
-- tells an attacker nothing about the clinic.
drop policy if exists "owner manages link codes" on public.clinic_link_codes;
create policy "owner manages link codes" on public.clinic_link_codes
  for all to authenticated
  using (public.is_clinic_owner(clinic_id))
  with check (public.is_clinic_owner(clinic_id));

-- ── clinic_clinicians ──
drop policy if exists "clinician reads own attachments" on public.clinic_clinicians;
drop policy if exists "owner reads clinic attachments"  on public.clinic_clinicians;
drop policy if exists "owner ends attachments"          on public.clinic_clinicians;

create policy "clinician reads own attachments" on public.clinic_clinicians
  for select to authenticated using (auth_user_id = auth.uid());
create policy "owner reads clinic attachments" on public.clinic_clinicians
  for select to authenticated using (public.is_clinic_owner(clinic_id));
create policy "owner ends attachments" on public.clinic_clinicians
  for update to authenticated
  using (public.is_clinic_owner(clinic_id))
  with check (public.is_clinic_owner(clinic_id));

-- ── clinician_activity ── the clinician owns their record; the owner sees
-- what happened in their own clinic and nothing from anywhere else.
drop policy if exists "clinician reads own activity" on public.clinician_activity;
drop policy if exists "owner reads clinic activity"  on public.clinician_activity;

create policy "clinician reads own activity" on public.clinician_activity
  for select to authenticated using (clinician_id = public.my_clinician_id());
create policy "owner reads clinic activity" on public.clinician_activity
  for select to authenticated using (public.is_clinic_owner(clinic_id));

-- ── clinician_ratings ── an owner writes one for their own clinic; the
-- clinician can always read what was said about them.
drop policy if exists "clinician reads own ratings" on public.clinician_ratings;
drop policy if exists "owner writes ratings"        on public.clinician_ratings;

create policy "clinician reads own ratings" on public.clinician_ratings
  for select to authenticated using (clinician_id = public.my_clinician_id());
create policy "owner writes ratings" on public.clinician_ratings
  for all to authenticated
  using (public.is_clinic_owner(clinic_id))
  with check (public.is_clinic_owner(clinic_id));

-- ════════════════════════════════════════════════════════════════════
-- The clinician's own profile
-- ════════════════════════════════════════════════════════════════════

create or replace function public.save_my_clinician_profile(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid  uuid := auth.uid();
  v_name text := nullif(trim(coalesce(p->>'full_name', '')), '');
  v_id   uuid;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'error', 'Sign in first');
  end if;
  if v_name is null then
    return jsonb_build_object('ok', false, 'error', 'Your name is required');
  end if;

  insert into public.clinicians (
    auth_user_id, full_name, profession, cadre, registration_no, registration_body,
    qualification, years_experience, phone, email, district, sub_county, village,
    address, languages, bio, updated_at
  ) values (
    v_uid, v_name, p->>'profession', p->>'cadre', p->>'registration_no', p->>'registration_body',
    p->>'qualification', nullif(p->>'years_experience','')::integer, p->>'phone', lower(nullif(p->>'email','')),
    p->>'district', p->>'sub_county', p->>'village', p->>'address', p->>'languages', p->>'bio', now()
  )
  on conflict (auth_user_id) do update set
    full_name         = excluded.full_name,
    profession        = coalesce(excluded.profession,        public.clinicians.profession),
    cadre             = coalesce(excluded.cadre,             public.clinicians.cadre),
    registration_no   = coalesce(excluded.registration_no,   public.clinicians.registration_no),
    registration_body = coalesce(excluded.registration_body, public.clinicians.registration_body),
    qualification     = coalesce(excluded.qualification,     public.clinicians.qualification),
    years_experience  = coalesce(excluded.years_experience,  public.clinicians.years_experience),
    phone             = coalesce(excluded.phone,             public.clinicians.phone),
    email             = coalesce(excluded.email,             public.clinicians.email),
    district          = coalesce(excluded.district,          public.clinicians.district),
    sub_county        = coalesce(excluded.sub_county,        public.clinicians.sub_county),
    village           = coalesce(excluded.village,           public.clinicians.village),
    address           = coalesce(excluded.address,           public.clinicians.address),
    languages         = coalesce(excluded.languages,         public.clinicians.languages),
    bio               = coalesce(excluded.bio,               public.clinicians.bio),
    updated_at        = now()
  returning id into v_id;

  return jsonb_build_object('ok', true, 'id', v_id);
exception when others then
  return jsonb_build_object('ok', false, 'error', sqlerrm);
end;
$$;
grant execute on function public.save_my_clinician_profile(jsonb) to authenticated;

-- Everything the clinician's own home screen needs, in one round trip —
-- because it is opened on a phone on a Ugandan connection.
create or replace function public.my_clinician_home()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id      uuid := public.my_clinician_id();
  v_profile jsonb;
  v_links   jsonb;
  v_stats   jsonb;
  v_ratings jsonb;
begin
  if v_id is null then
    return jsonb_build_object('ok', false, 'error', 'no clinician profile');
  end if;

  select to_jsonb(c) into v_profile from public.clinicians c where c.id = v_id;

  -- Expire anything whose time has quietly run out before reporting it as live.
  update public.clinic_clinicians
     set status = 'expired', ended_at = coalesce(ended_at, expires_at), ended_by = 'expired'
   where clinician_id = v_id and status = 'active'
     and expires_at is not null and expires_at < now();

  select coalesce(jsonb_agg(x order by x->>'started_at' desc), '[]'::jsonb) into v_links
    from (
      select jsonb_build_object(
        'id', cc.id, 'clinic_id', cc.clinic_id, 'clinic_name', cl.name,
        'clinic_district', cl.district, 'status', cc.status, 'role', cc.role,
        'started_at', cc.started_at, 'expires_at', cc.expires_at, 'ended_at', cc.ended_at,
        'ended_by', cc.ended_by,
        'treatments', (select count(*) from public.clinician_activity a where a.stint_id = cc.id)
      ) as x
      from public.clinic_clinicians cc
      left join public.clinics cl on cl.id = cc.clinic_id
      where cc.clinician_id = v_id
    ) s;

  select jsonb_build_object(
    'treatments',  count(*),
    'clinics',     count(distinct clinic_id),
    'first_seen',  min(occurred_at),
    'last_seen',   max(occurred_at),
    'conditions',  (
      select coalesce(jsonb_agg(jsonb_build_object('condition', cond, 'n', n) order by n desc), '[]'::jsonb)
        from (select condition as cond, count(*) as n
                from public.clinician_activity
               where clinician_id = v_id and condition is not null
               group by condition order by count(*) desc limit 12) t
    )
  ) into v_stats
  from public.clinician_activity where clinician_id = v_id;

  select coalesce(jsonb_agg(jsonb_build_object(
      'clinic_name', cl.name, 'rating', r.rating, 'care', r.care,
      'punctuality', r.punctuality, 'record_keeping', r.record_keeping,
      'teamwork', r.teamwork, 'would_rehire', r.would_rehire,
      'reference_note', r.reference_note, 'rater_name', r.rater_name,
      'created_at', r.created_at) order by r.created_at desc), '[]'::jsonb)
    into v_ratings
    from public.clinician_ratings r
    left join public.clinics cl on cl.id = r.clinic_id
   where r.clinician_id = v_id;

  return jsonb_build_object('ok', true, 'profile', v_profile,
    'links', v_links, 'stats', v_stats, 'ratings', v_ratings);
end;
$$;
grant execute on function public.my_clinician_home() to authenticated;

-- ════════════════════════════════════════════════════════════════════
-- The handshake
-- ════════════════════════════════════════════════════════════════════

-- Confusable characters are left out on purpose: this code gets read off
-- a screen and typed by somebody whose camera would not focus.
create or replace function public.gen_link_code()
returns text
language plpgsql
as $$
declare
  alphabet text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  out_code text := '';
  i        int;
begin
  for i in 1..8 loop
    out_code := out_code || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return out_code;
end;
$$;

create or replace function public.create_clinic_link_code(
  p_hours       integer default 24,
  p_max_uses    integer default 1,
  p_access_days integer default 30,
  p_role        text    default 'visiting_clinician'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clinic_id uuid;
  v_code      text;
  v_id        uuid;
  v_try       int := 0;
begin
  select pu.clinic_id into v_clinic_id
    from public.portal_users pu
   where pu.auth_user_id = auth.uid()
     and pu.is_active = true
     and coalesce(pu.staff_role,'owner') = 'owner'
   limit 1;

  if v_clinic_id is null then
    return jsonb_build_object('ok', false, 'error', 'Only the clinic owner can invite a clinician');
  end if;
  if p_role not in ('visiting_clinician','clinician','nurse') then
    return jsonb_build_object('ok', false, 'error', 'Invalid role');
  end if;

  loop
    v_try := v_try + 1;
    v_code := public.gen_link_code();
    begin
      insert into public.clinic_link_codes
        (clinic_id, code, created_by, role, access_days, expires_at, max_uses)
      values
        (v_clinic_id, v_code, auth.uid(), p_role,
         greatest(1, least(coalesce(p_access_days, 30), 365)),
         now() + (greatest(1, least(coalesce(p_hours, 24), 720)) || ' hours')::interval,
         greatest(1, least(coalesce(p_max_uses, 1), 50)))
      returning id into v_id;
      exit;
    exception when unique_violation then
      if v_try >= 6 then
        return jsonb_build_object('ok', false, 'error', 'Could not make a code, try again');
      end if;
    end;
  end loop;

  return jsonb_build_object('ok', true, 'id', v_id, 'code', v_code,
    'clinic_id', v_clinic_id,
    'clinic_name', (select name from public.clinics where id = v_clinic_id),
    'expires_at', (select expires_at from public.clinic_link_codes where id = v_id),
    'access_days', (select access_days from public.clinic_link_codes where id = v_id));
end;
$$;
grant execute on function public.create_clinic_link_code(integer, integer, integer, text) to authenticated;

-- Scanning the QR, or typing the code, lands here.
create or replace function public.redeem_clinic_link_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code   public.clinic_link_codes%rowtype;
  v_cid    uuid := public.my_clinician_id();
  v_stint  uuid;
  v_exp    timestamptz;
begin
  if v_cid is null then
    return jsonb_build_object('ok', false, 'error', 'Finish your clinician profile first');
  end if;

  select * into v_code from public.clinic_link_codes
   where upper(code) = upper(trim(coalesce(p_code, ''))) limit 1;

  -- One message for "no such code" and "expired code": a stranger holding a
  -- guess must not be told which of the two it was.
  if v_code.id is null or v_code.revoked or v_code.expires_at < now()
     or v_code.uses >= v_code.max_uses then
    return jsonb_build_object('ok', false, 'error', 'That code is not valid. Ask the clinic for a new one.');
  end if;

  v_exp := now() + (v_code.access_days || ' days')::interval;

  -- Coming back to a clinic you already work at renews the access rather
  -- than making a second record of the same job.
  select id into v_stint from public.clinic_clinicians
   where clinician_id = v_cid and clinic_id = v_code.clinic_id
     and status = 'active' limit 1;

  if v_stint is not null then
    update public.clinic_clinicians
       set expires_at = greatest(coalesce(expires_at, now()), v_exp),
           role = v_code.role
     where id = v_stint;
  else
    insert into public.clinic_clinicians
      (clinic_id, clinician_id, auth_user_id, status, role, started_at, expires_at,
       joined_via, link_code_id)
    values
      (v_code.clinic_id, v_cid, auth.uid(), 'active', v_code.role, now(), v_exp,
       'qr', v_code.id)
    returning id into v_stint;
  end if;

  update public.clinic_link_codes set uses = uses + 1 where id = v_code.id;

  return jsonb_build_object('ok', true,
    'stint_id',   v_stint,
    'clinic_id',  v_code.clinic_id,
    'clinic_name', (select name from public.clinics where id = v_code.clinic_id),
    'role',       v_code.role,
    'expires_at', v_exp);
end;
$$;
grant execute on function public.redeem_clinic_link_code(text) to authenticated;

-- ════════════════════════════════════════════════════════════════════
-- What the owner sees, and what they may say
-- ════════════════════════════════════════════════════════════════════

create or replace function public.clinic_clinicians_list()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clinic_id uuid;
  v_out       jsonb;
begin
  select pu.clinic_id into v_clinic_id
    from public.portal_users pu
   where pu.auth_user_id = auth.uid() and pu.is_active = true
     and coalesce(pu.staff_role,'owner') = 'owner' limit 1;

  if v_clinic_id is null then
    return jsonb_build_object('ok', false, 'error', 'Only the clinic owner can see this');
  end if;

  update public.clinic_clinicians
     set status = 'expired', ended_at = coalesce(ended_at, expires_at), ended_by = 'expired'
   where clinic_id = v_clinic_id and status = 'active'
     and expires_at is not null and expires_at < now();

  select coalesce(jsonb_agg(x order by x->>'started_at' desc), '[]'::jsonb) into v_out
    from (
      select jsonb_build_object(
        'stint_id', cc.id, 'clinician_id', c.id, 'full_name', c.full_name,
        'profession', c.profession, 'cadre', c.cadre, 'phone', c.phone,
        'registration_no', c.registration_no, 'district', c.district,
        'status', cc.status, 'role', cc.role, 'started_at', cc.started_at,
        'expires_at', cc.expires_at, 'ended_at', cc.ended_at, 'ended_by', cc.ended_by,
        'treatments', (select count(*) from public.clinician_activity a
                        where a.stint_id = cc.id),
        'last_seen',  (select max(a.occurred_at) from public.clinician_activity a
                        where a.stint_id = cc.id),
        'rated',      exists (select 1 from public.clinician_ratings r where r.stint_id = cc.id),
        'rating',     (select r.rating from public.clinician_ratings r where r.stint_id = cc.id)
      ) as x
      from public.clinic_clinicians cc
      join public.clinicians c on c.id = cc.clinician_id
      where cc.clinic_id = v_clinic_id
    ) s;

  return jsonb_build_object('ok', true, 'clinicians', v_out);
end;
$$;
grant execute on function public.clinic_clinicians_list() to authenticated;

-- Who one clinician treated, INSIDE this clinic. The patient names in this
-- answer come from the clinic's own records and stay in the clinic's own
-- portal — they are not in clinician_activity and do not travel.
create or replace function public.clinic_clinician_detail(p_stint_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cc   public.clinic_clinicians%rowtype;
  v_work jsonb;
  v_days jsonb;
begin
  select * into v_cc from public.clinic_clinicians where id = p_stint_id;
  if v_cc.id is null or not public.is_clinic_owner(v_cc.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'Not your clinic');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'created_at', cd.created_at,
      'patient_name', cd.patient_name,
      'case_code', cd.case_code,
      'diagnosis', cd.confirmed_diagnosis,
      'severity', cd.severity) order by cd.created_at desc), '[]'::jsonb)
    into v_work
    from public.clinic_diagnoses cd
   where cd.clinic_id = v_cc.clinic_id
     and cd.clinician_id = v_cc.auth_user_id
     and cd.created_at >= v_cc.started_at
     and (v_cc.ended_at is null or cd.created_at <= v_cc.ended_at)
   limit 300;

  select coalesce(jsonb_agg(jsonb_build_object('day', d, 'n', n) order by d), '[]'::jsonb)
    into v_days
    from (select date_trunc('day', occurred_at)::date as d, count(*) as n
            from public.clinician_activity
           where stint_id = p_stint_id
           group by 1 order by 1 desc limit 60) t;

  return jsonb_build_object('ok', true, 'work', v_work, 'by_day', v_days);
end;
$$;
grant execute on function public.clinic_clinician_detail(uuid) to authenticated;

create or replace function public.end_clinician_stint(
  p_stint_id uuid,
  p_reason   text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cc    public.clinic_clinicians%rowtype;
  v_who   text;
begin
  select * into v_cc from public.clinic_clinicians where id = p_stint_id;
  if v_cc.id is null then
    return jsonb_build_object('ok', false, 'error', 'Not found');
  end if;

  if public.is_clinic_owner(v_cc.clinic_id) then
    v_who := 'owner';
  elsif v_cc.auth_user_id = auth.uid() then
    v_who := 'clinician';
  else
    return jsonb_build_object('ok', false, 'error', 'Not allowed');
  end if;

  update public.clinic_clinicians
     set status = 'ended', ended_at = now(), ended_by = v_who,
         end_reason = nullif(trim(coalesce(p_reason,'')), '')
   where id = p_stint_id;

  return jsonb_build_object('ok', true, 'ended_by', v_who);
end;
$$;
grant execute on function public.end_clinician_stint(uuid, text) to authenticated;

create or replace function public.rate_clinician(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cc  public.clinic_clinicians%rowtype;
  v_r   int := nullif(p->>'rating','')::int;
begin
  select * into v_cc from public.clinic_clinicians where id = (p->>'stint_id')::uuid;
  if v_cc.id is null or not public.is_clinic_owner(v_cc.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'Not your clinic');
  end if;
  if v_r is null or v_r < 1 or v_r > 5 then
    return jsonb_build_object('ok', false, 'error', 'Give a rating from 1 to 5');
  end if;

  insert into public.clinician_ratings (
    clinic_id, clinician_id, stint_id, rated_by, rater_name, rating,
    care, punctuality, record_keeping, teamwork, would_rehire, reference_note
  ) values (
    v_cc.clinic_id, v_cc.clinician_id, v_cc.id, auth.uid(),
    (select full_name from public.portal_users where auth_user_id = auth.uid() limit 1),
    v_r,
    nullif(p->>'care','')::int, nullif(p->>'punctuality','')::int,
    nullif(p->>'record_keeping','')::int, nullif(p->>'teamwork','')::int,
    nullif(p->>'would_rehire','')::boolean,
    nullif(trim(coalesce(p->>'reference_note','')), '')
  )
  on conflict (stint_id) do update set
    rating = excluded.rating, care = excluded.care,
    punctuality = excluded.punctuality, record_keeping = excluded.record_keeping,
    teamwork = excluded.teamwork, would_rehire = excluded.would_rehire,
    reference_note = excluded.reference_note;

  return jsonb_build_object('ok', true);
exception when others then
  return jsonb_build_object('ok', false, 'error', sqlerrm);
end;
$$;
grant execute on function public.rate_clinician(jsonb) to authenticated;

-- The reference an owner reads BEFORE letting somebody in. Counts,
-- conditions and what other owners said — and not one patient.
create or replace function public.clinician_reference(p_clinician_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ok boolean;
begin
  -- Readable by the clinician themselves, or by an owner whose clinic they
  -- are (or were) attached to. Not by the world.
  select (c.auth_user_id = auth.uid())
      or exists (select 1 from public.clinic_clinicians cc
                  where cc.clinician_id = c.id and public.is_clinic_owner(cc.clinic_id))
    into v_ok
    from public.clinicians c where c.id = p_clinician_id;

  if not coalesce(v_ok, false) then
    return jsonb_build_object('ok', false, 'error', 'Not allowed');
  end if;

  return jsonb_build_object('ok', true,
    'profile', (select jsonb_build_object(
        'full_name', full_name, 'profession', profession, 'cadre', cadre,
        'qualification', qualification, 'registration_no', registration_no,
        'registration_body', registration_body, 'years_experience', years_experience,
        'district', district, 'languages', languages, 'bio', bio)
      from public.clinicians where id = p_clinician_id),
    'stints', (select coalesce(jsonb_agg(jsonb_build_object(
        'clinic_name', cl.name, 'district', cl.district,
        'started_at', cc.started_at, 'ended_at', cc.ended_at, 'status', cc.status,
        'treatments', (select count(*) from public.clinician_activity a where a.stint_id = cc.id)
      ) order by cc.started_at desc), '[]'::jsonb)
      from public.clinic_clinicians cc left join public.clinics cl on cl.id = cc.clinic_id
      where cc.clinician_id = p_clinician_id),
    'totals', (select jsonb_build_object(
        'treatments', count(*), 'clinics', count(distinct clinic_id))
      from public.clinician_activity where clinician_id = p_clinician_id),
    'conditions', (select coalesce(jsonb_agg(jsonb_build_object('condition', cond, 'n', n) order by n desc), '[]'::jsonb)
      from (select condition as cond, count(*) as n from public.clinician_activity
             where clinician_id = p_clinician_id and condition is not null
             group by condition order by count(*) desc limit 12) t),
    'ratings', (select coalesce(jsonb_agg(jsonb_build_object(
        'clinic_name', cl.name, 'rating', r.rating, 'would_rehire', r.would_rehire,
        'reference_note', r.reference_note, 'created_at', r.created_at) order by r.created_at desc), '[]'::jsonb)
      from public.clinician_ratings r left join public.clinics cl on cl.id = r.clinic_id
      where r.clinician_id = p_clinician_id),
    'average', (select round(avg(rating)::numeric, 1) from public.clinician_ratings
                 where clinician_id = p_clinician_id)
  );
end;
$$;
grant execute on function public.clinician_reference(uuid) to authenticated;

-- ════════════════════════════════════════════════════════════════════
-- "Every single thing is logged automatically"
--
-- A trigger, not a client call. A log the phone is asked to write is a
-- log that is missing exactly when it matters — the consultation that
-- was saved from the offline outbox, the one the app crashed after, the
-- one a future screen forgets to call. The row goes in beside the
-- treatment or not at all.
--
-- It copies the CONDITION and the DAY. It does not copy the patient,
-- and there is nowhere in clinician_activity to put one.
-- ════════════════════════════════════════════════════════════════════
create or replace function public.log_clinician_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cid   uuid;
  v_stint uuid;
begin
  if new.clinician_id is null then return new; end if;

  select id into v_cid from public.clinicians where auth_user_id = new.clinician_id limit 1;
  if v_cid is null then return new; end if;   -- clinic staff, not a portal clinician

  select id into v_stint from public.clinic_clinicians
   where clinician_id = v_cid and clinic_id = new.clinic_id
   order by (status = 'active') desc, started_at desc limit 1;

  insert into public.clinician_activity
    (clinician_id, clinic_id, stint_id, kind, condition, severity, occurred_at)
  values
    (v_cid, new.clinic_id, v_stint, 'treatment',
     nullif(trim(coalesce(new.confirmed_diagnosis, '')), ''),
     new.severity, coalesce(new.created_at, now()));

  return new;
exception when others then
  -- A failed log must never cost a clinic the consultation it was logging.
  return new;
end;
$$;

drop trigger if exists trg_log_clinician_activity on public.clinic_diagnoses;
create trigger trg_log_clinician_activity
  after insert on public.clinic_diagnoses
  for each row execute function public.log_clinician_activity();

-- ── The role a visiting clinician holds ─────────────────────────────
-- portal_users.staff_role is constrained to a known list. A clinician who
-- arrives by QR is not a member of staff and has no row there, but the
-- constraint is widened so an owner can convert one into permanent staff
-- later without a second migration.
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'portal_users_staff_role_check') then
    alter table public.portal_users drop constraint portal_users_staff_role_check;
  end if;
  alter table public.portal_users
    add constraint portal_users_staff_role_check
    check (staff_role in ('owner','clinician','nurse','receptionist','salesperson','visiting_clinician'));
end $$;

select 'clinician portal ready' as result;


-- ╔══════════════════════════════════════════════════════════════════════
-- ║  PART 2 of 3 — Owner-only corrections, and the inventory hole it closes
-- ║  source: supabase/migrations/20260912_owner_corrections.sql
-- ╚══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════
-- Correcting what was already recorded — and only the owner may do it
-- ════════════════════════════════════════════════════════════════════
--
-- A clinic asked to be able to fix what they had already saved: edit or
-- delete a quick sale, add the drug or the lab test or the money that was
-- forgotten on a treatment, and correct or remove a patient — "this is only
-- done in the main account, not sub accounts".
--
-- ── WHY THIS IS A MIGRATION AND NOT A SCREEN ────────────────────────
--
-- The screen cannot enforce that. Today every one of these tables is open to
-- every member of staff:
--
--   qs_clinic_write            for all using (active portal_user, same clinic)
--   clinic_patients_staff_manage    the same shape
--
-- "for all" is insert, update AND delete, and the check is membership, not
-- role. So a receptionist or a visiting clinician can already delete a sale
-- or a patient with a REST call — hiding the button in the app changes
-- nothing about that. The permission has to live in the database.
--
-- ── AND A HOLE FOUND ON THE WAY ─────────────────────────────────────
--
-- `adjust_inventory`, `deduct_inventory` and `get_clinic_stock` are all
-- `security definer`, which means they run as the owner of the function and
-- RLS never applies to them. None of the three checked that the CALLER
-- belongs to p_clinic_id — only that the item did. Any authenticated Homatt
-- user, including a patient account or a clinician attached to a different
-- clinic, could read another clinic's stock list and adjust its quantities,
-- given the ids.
--
-- That is fixed here, because this migration's "put the stock back" path
-- calls adjust_inventory, and building an owner-only feature on a function
-- anyone can call would be pointless.
--
-- ── THE RULES THE CORRECTIONS FOLLOW ────────────────────────────────
--
-- 1. A sale that is deleted or reduced PUTS THE STOCK BACK. A sale removed
--    without returning the stock makes the shelf count drift silently, which
--    is a worse fault than the wrong sale — nobody sees it until a count.
-- 2. Every correction writes an audit row: who, when, what, from, to. A
--    clinic's books changing with no trace is its own kind of harm, and the
--    owner asking for this is also the person it protects.
-- 3. A patient with any history is ARCHIVED, never destroyed. Their
--    treatments are a medical record. A patient with no visits and no sales
--    — the typo that made a duplicate, which is the common case — is deleted
--    outright, because there is nothing to lose.
-- 4. Nothing here invents a number. A correction records what a person typed.

-- ── 0. Who is the main account ──────────────────────────────────────
--
-- The clinic's own owner login. Deliberately NOT "anyone who is not a
-- visiting clinician": a receptionist and a nurse are sub-accounts too, and
-- the request was specific.
create or replace function public.is_clinic_main_account(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portal_users pu
    where pu.auth_user_id = auth.uid()
      and pu.is_active = true
      and pu.clinic_id = p_clinic_id
      and coalesce(pu.staff_role, 'owner') = 'owner'
  );
$$;

grant execute on function public.is_clinic_main_account(uuid) to authenticated;

-- Staff of this clinic at all, of any role. Used by the inventory fix below.
create or replace function public.is_clinic_staff(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portal_users pu
    where pu.auth_user_id = auth.uid()
      and pu.is_active = true
      and pu.clinic_id = p_clinic_id
  );
$$;

grant execute on function public.is_clinic_staff(uuid) to authenticated;

-- `homatt_norm_phone` comes from 20260615_unified_patient_identity.sql and is
-- what delete_clinic_patient below counts a patient's history with. Restated
-- here, identically, because a missing function inside a plpgsql body is
-- resolved at RUN time — so a database that skipped that migration would
-- accept this one and then fail on the first patient somebody tried to
-- remove. `create or replace` with the same body is a no-op where it exists.
create or replace function public.homatt_norm_phone(p text)
returns text
language sql
immutable
as $$
  select case
    when p is null then null
    when length(regexp_replace(p, '\D', '', 'g')) < 9 then null
    else right(regexp_replace(p, '\D', '', 'g'), 9)
  end;
$$;

-- ── 1. The audit trail ──────────────────────────────────────────────
create table if not exists public.clinic_record_edits (
  id           uuid primary key default gen_random_uuid(),
  clinic_id    uuid not null references public.clinics(id) on delete cascade,
  record_type  text not null,          -- 'quick_sale' | 'visit' | 'patient'
  record_id    uuid,
  action       text not null,          -- 'edit' | 'delete' | 'archive'
  before_json  jsonb,
  after_json   jsonb,
  reason       text,
  edited_by    uuid references auth.users(id),
  created_at   timestamptz default now()
);

create index if not exists idx_record_edits_clinic
  on public.clinic_record_edits (clinic_id, created_at desc);

alter table public.clinic_record_edits enable row level security;

-- Readable by the clinic's staff; written only through the RPCs below, which
-- are security definer. No direct insert policy on purpose — an audit row a
-- client can forge is not an audit row.
drop policy if exists "record_edits_read" on public.clinic_record_edits;
create policy "record_edits_read" on public.clinic_record_edits
  for select using (public.is_clinic_staff(clinic_id));

-- ── 2. Close the inventory hole ─────────────────────────────────────
--
-- TWO FAULTS WERE FOUND HERE, and the first one stopped this whole migration
-- applying to any real clinic. Both are recorded because the second is the
-- trap waiting for whoever fixes the first.
--
-- 1. IT COULD NOT BE APPLIED AT ALL. This was written as a bare
--    `create or replace` returning TEN columns. `20260710_inventory_expiry.sql`
--    had already redefined get_clinic_stock with THIRTEEN — it added
--    expiry_date, is_expired and is_expiring_soon, and dropped the old
--    signature first precisely because the return type was changing. Postgres
--    refuses to change a function's OUT parameters in place:
--
--      ERROR:  cannot change return type of existing function
--      DETAIL: Row type defined by OUT parameters is different.
--      HINT:   Use DROP FUNCTION get_clinic_stock(uuid) first.
--
--    And that error is fatal to everything around it. The Supabase SQL Editor
--    and the Management API send a whole script as ONE query string, which
--    Postgres runs in one implicit transaction — verified: two tables created
--    before a deliberate error in the same string, and neither survived. So
--    one red line about a function nobody has heard of would silently discard
--    the entire paste: the clinician portal, these corrections and the
--    flowsheet, all rolled back together.
--
-- 2. AND THE OBVIOUS FIX IS WORSE THAN THE BUG. Adding a bare
--    `drop function` would let it run — and would permanently remove
--    expiry_date, is_expired and is_expiring_soon from what the stock screen
--    receives. dashboard.html reads all three: it filters expiring stock,
--    sorts by expiry urgency and draws the EXPIRED and EXP SOON badges, and
--    its own client-side recompute derives the flags from expiry_date, which
--    would be gone too — so it would return false for everything. A clinic
--    would watch every expiry warning go dark on a shelf of real medicines,
--    with nothing on screen to say the warnings had stopped rather than that
--    nothing was expiring.
--
-- So: drop it explicitly, and put back all THIRTEEN columns with the caller
-- check added. The only thing this migration was ever meant to change here is
-- who may call it.
drop function if exists public.get_clinic_stock(uuid);

create or replace function public.get_clinic_stock(p_clinic_id uuid)
returns table (
  id               uuid,
  item_name        text,
  item_type        text,
  unit             text,
  quantity         numeric,
  min_threshold    numeric,
  reorder_level    numeric,
  unit_cost_ugx    numeric,
  is_low_stock     boolean,
  is_critical      boolean,
  expiry_date      date,
  is_expired       boolean,
  is_expiring_soon boolean
)
language sql
security definer
set search_path = public
as $$
  select
    id,
    item_name,
    item_type,
    unit,
    quantity,
    min_threshold,
    reorder_level,
    unit_cost_ugx,
    quantity <= min_threshold   as is_low_stock,
    quantity = 0                as is_critical,
    expiry_date,
    (expiry_date is not null and expiry_date < current_date)                as is_expired,
    (expiry_date is not null and expiry_date >= current_date
       and expiry_date < current_date + interval '60 days')                 as is_expiring_soon
  from public.clinic_inventory
  where clinic_id = p_clinic_id
    and is_active = true
    -- The caller must be staff of THIS clinic. Without this the function
    -- handed any authenticated user any clinic's shelves. This line is the
    -- entire point of touching the function; everything above it is the
    -- 20260710 definition, unchanged.
    and public.is_clinic_staff(p_clinic_id)
  order by (quantity <= min_threshold) desc, item_type, item_name;
$$;

grant execute on function public.get_clinic_stock(uuid) to authenticated;

create or replace function public.adjust_inventory(
  p_clinic_id    uuid,
  p_inventory_id uuid,
  p_qty_change   numeric,
  p_txn_type     text,
  p_notes        text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row   public.clinic_inventory%rowtype;
  v_after numeric;
begin
  -- The caller must be staff of this clinic. Restocking is an ordinary staff
  -- job, so this is staff and not owner — but it is no longer "anybody".
  if not public.is_clinic_staff(p_clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'not your clinic');
  end if;

  select * into v_row
  from public.clinic_inventory
  where id = p_inventory_id and clinic_id = p_clinic_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'item not found');
  end if;

  v_after := greatest(0, v_row.quantity + p_qty_change);

  update public.clinic_inventory
     set quantity = v_after, updated_at = now()
   where id = v_row.id;

  insert into public.clinic_inventory_txns
    (clinic_id, inventory_id, txn_type, quantity_change, quantity_after,
     unit_cost_ugx, notes, created_by)
  values
    (p_clinic_id, v_row.id, p_txn_type, p_qty_change, v_after,
     v_row.unit_cost_ugx, p_notes, auth.uid());

  return jsonb_build_object(
    'ok', true,
    'item_name', v_row.item_name,
    'quantity_after', v_after,
    'is_low_stock', v_after <= v_row.min_threshold
  );
end;
$$;

grant execute on function public.adjust_inventory(uuid, uuid, numeric, text, text) to authenticated;

-- ── 3. Quick sale: correct it, or take it off the books ─────────────
--
-- Editing the quantity moves the stock by the DIFFERENCE, in the right
-- direction: selling 2 where 3 was recorded puts 1 back on the shelf.
create or replace function public.edit_quick_sale(
  p_sale_id        uuid,
  p_quantity       integer default null,
  p_unit_price_ugx numeric default null,
  p_payment_method text    default null,
  p_reason         text    default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale   public.clinic_quick_sales%rowtype;
  v_before jsonb;
  v_qty    integer;
  v_price  numeric;
  v_method text;
  v_delta  numeric;
begin
  select * into v_sale from public.clinic_quick_sales where id = p_sale_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'sale not found');
  end if;

  if not public.is_clinic_main_account(v_sale.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'only the main account can correct a sale');
  end if;

  v_qty    := coalesce(p_quantity, v_sale.quantity);
  v_price  := coalesce(p_unit_price_ugx, v_sale.unit_price_ugx);
  v_method := coalesce(p_payment_method, v_sale.payment_method);

  if v_qty < 1 then
    return jsonb_build_object('ok', false, 'error', 'a sale of nothing is a deletion — use delete_quick_sale');
  end if;
  if v_price < 0 then
    return jsonb_build_object('ok', false, 'error', 'a price cannot be negative');
  end if;

  v_before := to_jsonb(v_sale);

  update public.clinic_quick_sales
     set quantity       = v_qty,
         unit_price_ugx = v_price,
         total_ugx      = v_qty * v_price,
         payment_method = v_method
   where id = v_sale.id;

  -- Stock follows the correction. Fewer sold than recorded puts the
  -- difference back; more sold takes it off.
  v_delta := v_sale.quantity - v_qty;
  if v_delta <> 0 and v_sale.drug_id is not null then
    perform public.adjust_inventory(
      v_sale.clinic_id, v_sale.drug_id, v_delta, 'adjustment',
      'Quick sale corrected: ' || v_sale.quantity || ' → ' || v_qty || ' × ' || coalesce(v_sale.unit, 'unit'));
  end if;

  insert into public.clinic_record_edits
    (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
  values
    (v_sale.clinic_id, 'quick_sale', v_sale.id, 'edit', v_before,
     to_jsonb((select s from public.clinic_quick_sales s where s.id = v_sale.id)),
     p_reason, auth.uid());

  return jsonb_build_object('ok', true, 'stock_returned', v_delta);
end;
$$;

grant execute on function public.edit_quick_sale(uuid, integer, numeric, text, text) to authenticated;

create or replace function public.delete_quick_sale(
  p_sale_id uuid,
  p_reason  text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale   public.clinic_quick_sales%rowtype;
  v_before jsonb;
begin
  select * into v_sale from public.clinic_quick_sales where id = p_sale_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'sale not found');
  end if;

  if not public.is_clinic_main_account(v_sale.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'only the main account can delete a sale');
  end if;

  v_before := to_jsonb(v_sale);

  -- The stock goes back on the shelf FIRST. If this failed after the row was
  -- gone there would be nothing left to say how much to return.
  if v_sale.drug_id is not null then
    perform public.adjust_inventory(
      v_sale.clinic_id, v_sale.drug_id, v_sale.quantity, 'adjustment',
      'Quick sale deleted: ' || v_sale.quantity || ' × ' || coalesce(v_sale.unit, 'unit') ||
      ' of ' || v_sale.drug_name || ' returned to stock');
  end if;

  delete from public.clinic_quick_sales where id = v_sale.id;

  insert into public.clinic_record_edits
    (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
  values
    (v_sale.clinic_id, 'quick_sale', v_sale.id, 'delete', v_before, null, p_reason, auth.uid());

  return jsonb_build_object('ok', true, 'stock_returned', v_sale.quantity);
end;
$$;

grant execute on function public.delete_quick_sale(uuid, text) to authenticated;

-- ── 4. A visit: the drug, the test or the money that was forgotten ──
--
-- Only the fields a correction should touch. The diagnosis itself, the
-- clinician who recorded it and the date are NOT editable here: changing who
-- was treated for what, after the fact, is not a correction, it is a
-- different record.
create or replace function public.edit_visit_record(
  p_visit_id            uuid,
  p_prescription_items  jsonb   default null,
  p_lab_tests_ordered   text[]  default null,
  p_consultation_fee    numeric default null,
  p_lab_fee             numeric default null,
  p_meds_fee            numeric default null,
  p_amount_paid         numeric default null,
  p_treatment_plan      text    default null,
  p_reason              text    default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row    public.clinic_diagnoses%rowtype;
  v_before jsonb;
  v_cons   numeric;
  v_lab    numeric;
  v_meds   numeric;
  v_total  numeric;
  v_paid   numeric;
  v_status text;
begin
  select * into v_row from public.clinic_diagnoses where id = p_visit_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'visit not found');
  end if;

  if not public.is_clinic_main_account(v_row.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'only the main account can correct a visit');
  end if;

  v_before := to_jsonb(v_row);

  v_cons := greatest(0, coalesce(p_consultation_fee, v_row.consultation_fee_ugx, 0));
  v_lab  := greatest(0, coalesce(p_lab_fee,          v_row.lab_fee_ugx,          0));
  v_meds := greatest(0, coalesce(p_meds_fee,         v_row.meds_fee_ugx,         0));

  /* THE TOTAL IS ONLY REBUILT FROM THE THREE FEES WHEN A FEE WAS ACTUALLY
   * GIVEN, and that condition is the whole of this fix.
   *
   * This line used to read `v_total := v_cons + v_lab + v_meds;`
   * unconditionally — including when the owner had touched nothing but a
   * misspelt lab test name. The three fee columns are not the only source of
   * a charge: FOLLOW-UP adds its extra charge straight onto
   * total_charged_ugx and never touches them —
   *
   *     update.total_charged_ugx = (Number(current.total_charged_ugx) || 0)
   *                              + extraCharge;        (dashboard.html)
   *
   * so on any visit that has had a follow-up, total_charged_ugx is
   * legitimately LARGER than the sum of the three, and rebuilding it deleted
   * the difference in silence.
   *
   * Concretely: a 30,000 visit plus a 30,000 follow-up charge is 60,000
   * billed and 30,000 paid — partial. The owner opens the dialog to fix a
   * typo in a lab test. The total is rewritten to 30,000, the clamp below
   * pulls amount_paid down to match, the status flips to 'paid', and the
   * clinic's 30,000 debt disappears from the owing list and from the month's
   * figures. Nothing on screen says a number changed.
   *
   * Correcting a lab test must not touch the money. */
  if p_consultation_fee is null and p_lab_fee is null and p_meds_fee is null then
    v_total := coalesce(v_row.total_charged_ugx, v_cons + v_lab + v_meds);
  else
    v_total := v_cons + v_lab + v_meds;
  end if;

  v_paid := greatest(0, coalesce(p_amount_paid, v_row.amount_paid, 0));

  /* MORE PAID THAN BILLED IS REFUSED — NOT CLAMPED, AND NOT ACCEPTED.
   *
   * This read `if v_paid > v_total then v_paid := v_total`, and that quietly
   * destroyed recorded receipts: a patient who had handed over 45,000 against
   * a total later corrected down to 30,000 lost 15,000 of payments, with no
   * trace outside the audit row.
   *
   * Simply removing the clamp is the other mistake. A slipped finger —
   * "99999" on an 18,000 bill — would then inflate the clinic's money-in
   * figure, and a wrong number in the books is what this whole feature exists
   * to fix.
   *
   * Both of those are the function deciding something only a person can. A
   * payment larger than the bill is either a typo or a genuine overpayment
   * that means the BILL is wrong, and those need opposite corrections. So it
   * is refused, in words, with both figures named.
   *
   * Only when the owner actually SUPPLIED an amount. A visit that already
   * carries more paid than billed — which a follow-up charge recorded in the
   * wrong order can produce — must still be correctable in every other
   * respect, or fixing its lab test becomes impossible. */
  if p_amount_paid is not null and v_paid > v_total then
    return jsonb_build_object('ok', false, 'error',
      'That records UGX ' || trim(to_char(v_paid, '999999999')) ||
      ' paid against a bill of UGX ' || trim(to_char(v_total, '999999999')) ||
      '. If the patient really paid that much, correct the bill first; if it ' ||
      'is a typo, correct the amount. Nothing has been changed.');
  end if;

  -- THE AMOUNT DECIDES THE STATUS, NOT A CHIP. Same rule the treatment screen
  -- already follows: nothing paid is pending, part of it is partial, the whole
  -- bill is paid — so a correction cannot record a debt as settled by mistake.
  v_status := case
    when v_total <= 0    then coalesce(v_row.payment_status, 'pending')
    when v_paid <= 0     then 'pending'
    when v_paid >= v_total then 'paid'
    else 'partial'
  end;

  update public.clinic_diagnoses
     set prescription_items   = coalesce(p_prescription_items, prescription_items),
         lab_tests_ordered    = coalesce(p_lab_tests_ordered,  lab_tests_ordered),
         treatment_plan       = coalesce(p_treatment_plan,     treatment_plan),
         consultation_fee_ugx = v_cons,
         lab_fee_ugx          = v_lab,
         meds_fee_ugx         = v_meds,
         total_charged_ugx    = v_total,
         amount_paid          = v_paid,
         payment_status       = v_status
   where id = v_row.id;

  insert into public.clinic_record_edits
    (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
  values
    (v_row.clinic_id, 'visit', v_row.id, 'edit', v_before,
     to_jsonb((select d from public.clinic_diagnoses d where d.id = v_row.id)),
     p_reason, auth.uid());

  return jsonb_build_object('ok', true, 'total_charged_ugx', v_total,
                            'amount_paid', v_paid, 'payment_status', v_status);
end;
$$;

grant execute on function public.edit_visit_record(uuid, jsonb, text[], numeric, numeric, numeric, numeric, text, text) to authenticated;

-- ── 5. A patient: correct one, and remove one safely ────────────────
create or replace function public.edit_clinic_patient(
  p_patient_id uuid,
  p_full_name  text default null,
  p_phone      text default null,
  p_notes      text default null,
  p_reason     text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row    public.clinic_patients%rowtype;
  v_before jsonb;
  v_name   text;
  v_phone  text;
begin
  select * into v_row from public.clinic_patients where id = p_patient_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'patient not found');
  end if;

  if not public.is_clinic_main_account(v_row.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'only the main account can edit a patient');
  end if;

  v_name  := nullif(btrim(coalesce(p_full_name, v_row.full_name)), '');
  v_phone := nullif(btrim(coalesce(p_phone,     v_row.phone)),     '');
  if v_name is null then
    return jsonb_build_object('ok', false, 'error', 'a patient needs a name');
  end if;
  if v_phone is null then
    return jsonb_build_object('ok', false, 'error', 'a patient needs a phone number');
  end if;

  -- The clinic already holds somebody else on that number. Say so plainly
  -- rather than letting the unique constraint surface as a database error.
  if exists (
    select 1 from public.clinic_patients p
    where p.clinic_id = v_row.clinic_id and p.phone = v_phone and p.id <> v_row.id
  ) then
    return jsonb_build_object('ok', false, 'error', 'another patient at this clinic already has that phone number');
  end if;

  v_before := to_jsonb(v_row);

  update public.clinic_patients
     set full_name  = v_name,
         phone      = v_phone,
         notes      = coalesce(p_notes, notes),
         updated_at = now()
   where id = v_row.id;

  insert into public.clinic_record_edits
    (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
  values
    (v_row.clinic_id, 'patient', v_row.id, 'edit', v_before,
     to_jsonb((select p from public.clinic_patients p where p.id = v_row.id)),
     p_reason, auth.uid());

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.edit_clinic_patient(uuid, text, text, text, text) to authenticated;

-- Archive rather than destroy, whenever there is anything to lose.
alter table public.clinic_patients
  add column if not exists archived_at timestamptz;

create or replace function public.delete_clinic_patient(
  p_patient_id uuid,
  p_reason     text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row    public.clinic_patients%rowtype;
  v_before jsonb;
  v_visits integer;
begin
  select * into v_row from public.clinic_patients where id = p_patient_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'patient not found');
  end if;

  if not public.is_clinic_main_account(v_row.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'only the main account can remove a patient');
  end if;

  v_before := to_jsonb(v_row);

  -- Does this person have a history? A visit is a medical record and is not
  -- ours to destroy to tidy a list.
  --
  -- The link is clinic_diagnoses, not bookings: a walk-in is recorded straight
  -- onto a diagnosis and never gets a booking at all, so counting bookings
  -- would report "no history" for most of a busy clinic's patients and delete
  -- them outright. `bookings` has no patient_phone column either.
  /* MATCHED THE WAY THE REST OF THIS CODEBASE MATCHES A PERSON, which this
   * did not, and it is the only thing standing between "archive" and a hard
   * DELETE.
   *
   * It compared raw strings. This project has a whole migration
   * (20260615_unified_patient_identity.sql) saying why that is unsafe —
   * "+256772123456, 0772123456 and 772123456 all resolve to the same person" —
   * it ships `homatt_norm_phone` for exactly this, and it indexes
   * clinic_patients on that function. clinic-intake.js normalises before
   * comparing too. Only this count did not.
   *
   * And the two functions in THIS file combine into the failure.
   * `edit_clinic_patient` above updates clinic_patients.full_name and phone
   * and deliberately leaves the historical clinic_diagnoses rows alone. So the
   * natural sequence — correct the patient's mistyped phone, then delete the
   * duplicate that the typo created — is precisely the sequence that makes
   * BOTH sides of the OR miss, counts zero visits, and hard-deletes somebody
   * with years of treatments behind them. Their clinic_diagnoses rows survive
   * but are orphaned, and the registration row goes.
   *
   * It fails safe now in the only direction that matters: a phone too short to
   * normalise falls back to the raw comparison rather than matching nothing,
   * and a name is compared case- and space-insensitively. Counting one visit
   * too many archives a duplicate that could have been deleted, which is
   * untidy. Counting one too few destroys a medical record. */
  select count(*) into v_visits
  from public.clinic_diagnoses d
  where d.clinic_id = v_row.clinic_id
    and (
      (public.homatt_norm_phone(v_row.phone) is not null
        and public.homatt_norm_phone(d.patient_phone) = public.homatt_norm_phone(v_row.phone))
      or
      (public.homatt_norm_phone(v_row.phone) is null
        and d.patient_phone is not null and d.patient_phone = v_row.phone)
      or
      /* Internal whitespace is collapsed too, not just trimmed. `btrim` alone
       * left "Okello  John" and "OKELLO JOHN" as different people — and a
       * double space in a typed name is one of the commonest ways the
       * duplicate this feature deletes gets created in the first place. */
      (d.patient_name is not null and v_row.full_name is not null
        and regexp_replace(lower(btrim(d.patient_name)), '\s+', ' ', 'g')
          = regexp_replace(lower(btrim(v_row.full_name)), '\s+', ' ', 'g'))
    );

  if v_visits > 0 then
    update public.clinic_patients
       set archived_at = now(), updated_at = now()
     where id = v_row.id;

    insert into public.clinic_record_edits
      (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
    values
      (v_row.clinic_id, 'patient', v_row.id, 'archive', v_before, null, p_reason, auth.uid());

    return jsonb_build_object('ok', true, 'archived', true, 'visits', v_visits);
  end if;

  -- Nothing to lose: the duplicate a typo made. Remove it.
  delete from public.clinic_patients where id = v_row.id;

  insert into public.clinic_record_edits
    (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
  values
    (v_row.clinic_id, 'patient', v_row.id, 'delete', v_before, null, p_reason, auth.uid());

  return jsonb_build_object('ok', true, 'archived', false, 'visits', 0);
end;
$$;

grant execute on function public.delete_clinic_patient(uuid, text) to authenticated;

-- ── 6. Shut the direct doors the RPCs replace ───────────────────────
--
-- With the corrections available as owner-only RPCs, a sub-account no longer
-- needs — and must not have — a direct UPDATE or DELETE on these tables. The
-- RPCs are security definer, so they keep working.
--
-- INSERT and SELECT stay open to all staff: recording a sale and registering
-- a patient are everyday work, and the clinician portal depends on both.
drop policy if exists "qs_clinic_write" on public.clinic_quick_sales;

drop policy if exists "qs_clinic_insert" on public.clinic_quick_sales;
create policy "qs_clinic_insert" on public.clinic_quick_sales
  for insert with check (public.is_clinic_staff(clinic_id));

drop policy if exists "qs_clinic_update_owner" on public.clinic_quick_sales;
create policy "qs_clinic_update_owner" on public.clinic_quick_sales
  for update using (public.is_clinic_main_account(clinic_id));

drop policy if exists "qs_clinic_delete_owner" on public.clinic_quick_sales;
create policy "qs_clinic_delete_owner" on public.clinic_quick_sales
  for delete using (public.is_clinic_main_account(clinic_id));

drop policy if exists "clinic_patients_staff_manage" on public.clinic_patients;

drop policy if exists "clinic_patients_staff_read" on public.clinic_patients;
create policy "clinic_patients_staff_read" on public.clinic_patients
  for select using (public.is_clinic_staff(clinic_id));

drop policy if exists "clinic_patients_staff_insert" on public.clinic_patients;
create policy "clinic_patients_staff_insert" on public.clinic_patients
  for insert with check (public.is_clinic_staff(clinic_id));

-- Staff may still correct the record they are in the middle of creating —
-- the treatment screen upserts a patient as it goes — but only the main
-- account may delete one.
drop policy if exists "clinic_patients_staff_update" on public.clinic_patients;
create policy "clinic_patients_staff_update" on public.clinic_patients
  for update using (public.is_clinic_staff(clinic_id));

drop policy if exists "clinic_patients_owner_delete" on public.clinic_patients;
create policy "clinic_patients_owner_delete" on public.clinic_patients
  for delete using (public.is_clinic_main_account(clinic_id));


-- ╔══════════════════════════════════════════════════════════════════════
-- ║  PART 3 of 3 — The vital flowsheet — readings, notes and monitoring orders
-- ║  source: supabase/migrations/20260916_vital_flowsheet.sql
-- ╚══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════
-- The vital flowsheet — a reading, the time it was taken, and what was
-- done about it
-- ════════════════════════════════════════════════════════════════════
--
-- "Monitor BP every 5 minutes" and "her pressure every morning for a month"
-- are the same question asked over two timescales: is this person getting
-- worse, holding, or responding? Today the app can answer neither. Vitals are
-- taken once, at intake, and written into `clinical_findings` as a sentence.
-- A sentence cannot be plotted, cannot be compared with the one before it, and
-- cannot be counted.
--
-- So: one row per reading, and a note that belongs to that reading.
--
-- ── A READING IS NEVER EDITED AND NEVER DELETED ─────────────────────
--
-- This is the one design decision in the file and it is deliberate. The rest
-- of this app can correct a sale, a fee or a patient's name, because those are
-- facts about an agreement and an agreement can be wrong. A vital sign is not
-- that. It is an observation of a person at an instant, and the instant is
-- gone. "Her pressure at 10:15 was 190/110" cannot be made untrue later; it
-- can only be marked as having been written down wrongly.
--
-- Rewriting one in place would also destroy the only thing the flowsheet is
-- for. Every delta, every arrow and every trend line is computed from the row
-- BEFORE — so silently changing a reading changes the meaning of its
-- neighbours too, and a chart somebody has already acted on becomes a
-- different chart with no trace.
--
-- So there is no update policy and no delete policy on the readings at all.
-- A mistake is VOIDED — struck through, with a reason and a name against it —
-- and a corrected reading is entered as its own row. The wrong one stays
-- visible and stays out of the arithmetic. That is how a paper observation
-- chart has always worked, and for the same reason.
--
-- ── WHO MAY DO WHAT ─────────────────────────────────────────────────
--
--   record a reading   any active member of this clinic's staff, including a
--                      visiting clinician. Taking observations is the work.
--   void one           the person who recorded it, or the main account. Not
--                      anybody else: striking out somebody else's observation
--                      is not a correction, it is an assertion about what they
--                      saw.
--   read them          this clinic's staff, and nobody else's.
--   destroy one        nobody. There is no delete policy. A row cannot be
--                      removed through the API by any role.
--
-- ── EVERY SECURITY-DEFINER FUNCTION CHECKS ITS CALLER ───────────────
--
-- The hole found in 20260912 — adjust_inventory, deduct_inventory and
-- get_clinic_stock all ran as the function's owner, so RLS never applied to
-- them, and none of the three checked that the CALLER belonged to the clinic
-- whose id was passed in. RLS on a table says nothing about a security-definer
-- function that touches it. Both functions below check the caller first,
-- before they look at anything else.

-- ── 1. The readings ─────────────────────────────────────────────────
create table if not exists public.vital_logs (
  id                uuid primary key default gen_random_uuid(),
  clinic_id         uuid not null references public.clinics(id) on delete cascade,

  -- WHO. A clinic patient where there is one; a walk-in treated once may have
  -- no patient row at all, and the visit is then the only identity there is.
  clinic_patient_id uuid,

  -- WHICH OCCASION. Null on purpose for the chronic case: somebody coming in
  -- every month to have their pressure taken is not a treatment each time, and
  -- requiring one would either invent empty visits or lose the readings.
  diagnosis_id      uuid,

  systolic          integer,
  diastolic         integer,
  pulse             integer,
  temp_c            numeric(4,1),
  resp_rate         integer,
  spo2              integer,
  weight_kg         numeric(5,1),

  /* MAP is GENERATED, not stored by the client and not recomputed on read.
   *
   * A derived number written by the app can disagree with the numbers it came
   * from — after a bad sync, an older build, a hand-written row — and there is
   * nothing on the far side to notice. A generated column cannot: Postgres
   * recomputes it from this row's own systolic and diastolic and there is no
   * way to write a different value into it.
   *
   * MAP = DBP + (SBP − DBP)/3. The same formula the phone uses, so the two can
   * never drift; the phone has it because the flowsheet must work with no
   * connection at all. */
  map_mmhg numeric(5,1) generated always as (
    case
      when systolic is not null and diastolic is not null
       and systolic > 0 and diastolic > 0 and diastolic <= systolic
      then round(diastolic + (systolic - diastolic) / 3.0, 1)
      else null
    end
  ) stored,

  /* WHEN THE READING WAS TAKEN, which is not when the row was written. A nurse
   * on a ward round writes four observations up at the end of it, and a phone
   * with no signal writes them whenever it next has one. `logged_at` is the
   * clinical fact and is what everything sorts and plots by; `created_at` is
   * the database's own bookkeeping. Keeping them apart is what makes a
   * retroactive entry honest rather than a lie about the clock. */
  logged_at         timestamptz not null default now(),
  back_entered      boolean not null default false,

  recorded_by       uuid references auth.users(id),
  recorded_by_name  text,
  -- 'manual' | 'intake' | 'dictation' — where the numbers came from, because
  -- a dictated reading and a typed one are not equally likely to be right.
  source            text not null default 'manual',

  -- Struck through, not erased. See the header.
  voided_at         timestamptz,
  voided_by         uuid references auth.users(id),
  void_reason       text,

  created_at        timestamptz default now(),

  /* A row with nothing measured in it is noise on a chart, and the commonest
   * way to get one is a half-finished form being saved. */
  constraint vital_logs_has_something check (
    systolic is not null or diastolic is not null or pulse is not null or
    temp_c is not null or resp_rate is not null or spo2 is not null or
    weight_kg is not null
  ),

  /* DELIBERATELY LOOSE. These reject what cannot be a living human, not what
   * is unlikely — a constraint tight enough to catch a typo is also tight
   * enough to reject a real reading from a patient in extremis, and a rejected
   * insert loses the observation entirely. The narrow, clinically-interesting
   * ranges are the app's job, where a questionable number can be queried on
   * screen with the patient still in the room. */
  constraint vital_logs_plausible check (
    (systolic  is null or systolic  between 30 and 300) and
    (diastolic is null or diastolic between 10 and 250) and
    (pulse     is null or pulse     between 15 and 320) and
    (temp_c    is null or temp_c    between 20 and 46)  and
    (resp_rate is null or resp_rate between 2  and 99)  and
    (spo2      is null or spo2      between 30 and 100) and
    (weight_kg is null or weight_kg between 0.3 and 400)
  )
);

-- Added separately so the table can gain them on a database that already has
-- an older shape, which `create table if not exists` alone would skip.
alter table public.vital_logs
  add column if not exists back_entered     boolean not null default false,
  add column if not exists recorded_by_name text,
  add column if not exists source           text not null default 'manual',
  add column if not exists voided_at        timestamptz,
  add column if not exists voided_by        uuid,
  add column if not exists void_reason      text,
  add column if not exists spo2             integer,
  add column if not exists resp_rate        integer,
  add column if not exists weight_kg        numeric(5,1);

-- The flowsheet always asks the same question: this patient, newest first.
create index if not exists idx_vital_logs_patient
  on public.vital_logs (clinic_id, clinic_patient_id, logged_at desc);
create index if not exists idx_vital_logs_visit
  on public.vital_logs (diagnosis_id, logged_at desc);

-- ── 2. The note tied to a reading ───────────────────────────────────
--
-- "190/110" and "gave labetalol 20mg IV" are one fact, not two. A note filed
-- against the patient with its own timestamp would end up minutes away from
-- the reading it explains — and on a chart where a fall of 30 mmHg is the
-- thing being judged, "before or after the drug" is the entire question. So
-- the note hangs off the reading's id and moves with it.
create table if not exists public.vital_notes (
  id            uuid primary key default gen_random_uuid(),
  vital_log_id  uuid not null references public.vital_logs(id) on delete cascade,
  clinic_id     uuid not null references public.clinics(id) on delete cascade,
  note_text     text not null,
  -- 'MEDICATION_GIVEN' | 'OBSERVATION' | 'DOCTOR_ORDER' | 'EVENT'
  action_type   text not null default 'OBSERVATION',
  author_id     uuid references auth.users(id),
  author_name   text,
  voided_at     timestamptz,
  voided_by     uuid references auth.users(id),
  created_at    timestamptz default now(),
  constraint vital_notes_not_empty check (length(btrim(note_text)) > 0)
);

alter table public.vital_notes
  add column if not exists author_name text,
  add column if not exists voided_at   timestamptz,
  add column if not exists voided_by   uuid;

create index if not exists idx_vital_notes_log
  on public.vital_notes (vital_log_id, created_at);

-- ── 3. The monitoring order ─────────────────────────────────────────
--
-- "Every 15 minutes" is an instruction from one person to whoever is on the
-- ward next, so it cannot live in the phone that received it. One active
-- watch per patient; starting a new one ends the old one, because two
-- intervals running on one patient is an argument, not an order.
create table if not exists public.vital_watch (
  id                uuid primary key default gen_random_uuid(),
  clinic_id         uuid not null references public.clinics(id) on delete cascade,
  clinic_patient_id uuid,
  diagnosis_id      uuid,
  interval_minutes  integer not null,
  reason            text,
  started_by        uuid references auth.users(id),
  started_by_name   text,
  started_at        timestamptz not null default now(),
  stopped_at        timestamptz,
  stopped_by        uuid references auth.users(id),
  created_at        timestamptz default now(),
  constraint vital_watch_interval check (interval_minutes between 1 and 1440)
);

create index if not exists idx_vital_watch_active
  on public.vital_watch (clinic_id, clinic_patient_id)
  where stopped_at is null;

-- ── 4. Row level security ───────────────────────────────────────────
alter table public.vital_logs  enable row level security;
alter table public.vital_notes enable row level security;
alter table public.vital_watch enable row level security;

-- `is_clinic_staff` comes from 20260912_owner_corrections.sql. Defined again
-- here, identically, so this migration can be applied to a database that has
-- not had that one yet — `create or replace` with the same body is a no-op
-- where it already exists.
create or replace function public.is_clinic_staff(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portal_users pu
    where pu.auth_user_id = auth.uid()
      and pu.is_active = true
      and pu.clinic_id = p_clinic_id
  );
$$;
grant execute on function public.is_clinic_staff(uuid) to authenticated;

-- Likewise `is_clinic_main_account`, which void_vital_log() calls. plpgsql
-- resolves a missing function at RUN time, not at create time — so without
-- this, a database that skipped 20260912 would accept this whole migration
-- and then fail on the first strike-out, which is exactly the kind of fault
-- that only appears in a clinic.
create or replace function public.is_clinic_main_account(p_clinic_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.portal_users pu
    where pu.auth_user_id = auth.uid()
      and pu.is_active = true
      and pu.clinic_id = p_clinic_id
      and coalesce(pu.staff_role, 'owner') = 'owner'
  );
$$;
grant execute on function public.is_clinic_main_account(uuid) to authenticated;

-- READ: this clinic's staff.
drop policy if exists "vital_logs_read" on public.vital_logs;
create policy "vital_logs_read" on public.vital_logs
  for select using (public.is_clinic_staff(clinic_id));

-- WRITE: this clinic's staff, and only as themselves. `recorded_by` is checked
-- against auth.uid() so a row cannot be filed under somebody else's name —
-- on an observation chart the signature is part of the observation.
drop policy if exists "vital_logs_insert" on public.vital_logs;
create policy "vital_logs_insert" on public.vital_logs
  for insert with check (
    public.is_clinic_staff(clinic_id)
    and (recorded_by is null or recorded_by = auth.uid())
  );

-- No UPDATE policy and no DELETE policy, on purpose. Voiding goes through
-- void_vital_log() below, which is the only path that can write those columns.

drop policy if exists "vital_notes_read" on public.vital_notes;
create policy "vital_notes_read" on public.vital_notes
  for select using (public.is_clinic_staff(clinic_id));

drop policy if exists "vital_notes_insert" on public.vital_notes;
create policy "vital_notes_insert" on public.vital_notes
  for insert with check (
    public.is_clinic_staff(clinic_id)
    and (author_id is null or author_id = auth.uid())
    -- and the reading it hangs off must be one of this clinic's own
    and exists (
      select 1 from public.vital_logs vl
      where vl.id = vital_log_id and vl.clinic_id = vital_notes.clinic_id
    )
  );

drop policy if exists "vital_watch_read" on public.vital_watch;
create policy "vital_watch_read" on public.vital_watch
  for select using (public.is_clinic_staff(clinic_id));

drop policy if exists "vital_watch_insert" on public.vital_watch;
create policy "vital_watch_insert" on public.vital_watch
  for insert with check (public.is_clinic_staff(clinic_id));

-- Stopping a watch is ordinary clinical work — the patient stabilised, or the
-- order was carried out. Any of this clinic's staff may, and the only thing
-- that may be changed is that it stopped.
drop policy if exists "vital_watch_stop" on public.vital_watch;
create policy "vital_watch_stop" on public.vital_watch
  for update using (public.is_clinic_staff(clinic_id))
  with check (public.is_clinic_staff(clinic_id));

-- ── 5. Voiding a reading ────────────────────────────────────────────
create or replace function public.void_vital_log(
  p_log_id uuid,
  p_reason text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row  public.vital_logs%rowtype;
begin
  select * into v_row from public.vital_logs where id = p_log_id;
  if not found then
    return jsonb_build_object('ok', false, 'error', 'No such reading.');
  end if;

  -- THE CALLER CHECK. This function runs as its owner and RLS never sees it,
  -- so without this any authenticated Homatt user — a patient account, a
  -- clinician attached to somewhere else — could strike out this clinic's
  -- observations given an id.
  if not public.is_clinic_staff(v_row.clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'Not your clinic.');
  end if;

  -- Whoever wrote it, or the main account. Striking out somebody else's
  -- observation is a statement about what they saw, and it needs the
  -- authority the clinic actually recognises.
  if v_row.recorded_by is distinct from auth.uid()
     and not public.is_clinic_main_account(v_row.clinic_id) then
    return jsonb_build_object('ok', false, 'error',
      'Only the person who recorded this reading, or the main account, can strike it out.');
  end if;

  if v_row.voided_at is not null then
    return jsonb_build_object('ok', true, 'already', true);
  end if;

  if p_reason is null or length(btrim(p_reason)) = 0 then
    return jsonb_build_object('ok', false, 'error',
      'Say why it is being struck out.');
  end if;

  update public.vital_logs
     set voided_at = now(), voided_by = auth.uid(), void_reason = btrim(p_reason)
   where id = p_log_id;

  -- The same audit table the corrections feature writes to, where it exists.
  -- A clinic that has not applied that migration still gets the void; it just
  -- gets no second copy of the record of it.
  begin
    insert into public.clinic_record_edits
      (clinic_id, record_type, record_id, action, before_json, after_json, reason, edited_by)
    values (v_row.clinic_id, 'vital_log', p_log_id, 'void',
            to_jsonb(v_row), null, btrim(p_reason), auth.uid());
  exception when undefined_table then null;
  end;

  return jsonb_build_object('ok', true);
end $$;

grant execute on function public.void_vital_log(uuid, text) to authenticated;

-- ── 6. Reading a patient's flowsheet ────────────────────────────────
--
-- A plain select would do, and the app uses one. This exists for the case the
-- plain select cannot serve: a patient with no `clinic_patients` row, whose
-- readings are tied to visits instead, where the query is a join the client
-- would otherwise have to get right in four places.
create or replace function public.get_vital_flowsheet(
  p_clinic_id uuid,
  p_patient_id uuid default null,
  p_diagnosis_id uuid default null,
  p_since timestamptz default null,
  p_limit integer default 500
) returns setof public.vital_logs
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  -- Again: security definer, so the caller is checked here or not at all.
  if not public.is_clinic_staff(p_clinic_id) then
    return;
  end if;

  return query
    select vl.* from public.vital_logs vl
    where vl.clinic_id = p_clinic_id
      and (p_patient_id is null or vl.clinic_patient_id = p_patient_id)
      and (p_diagnosis_id is null or vl.diagnosis_id = p_diagnosis_id)
      and (p_since is null or vl.logged_at >= p_since)
    order by vl.logged_at desc
    limit greatest(1, least(coalesce(p_limit, 500), 2000));
end $$;

grant execute on function public.get_vital_flowsheet(uuid, uuid, uuid, timestamptz, integer) to authenticated;

-- ── 7. Starting and stopping a watch ────────────────────────────────
create or replace function public.start_vital_watch(
  p_clinic_id uuid,
  p_patient_id uuid,
  p_diagnosis_id uuid,
  p_interval_minutes integer,
  p_reason text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid; v_name text;
begin
  if not public.is_clinic_staff(p_clinic_id) then
    return jsonb_build_object('ok', false, 'error', 'Not your clinic.');
  end if;
  if p_interval_minutes is null or p_interval_minutes < 1 or p_interval_minutes > 1440 then
    return jsonb_build_object('ok', false, 'error', 'Choose an interval between 1 minute and a day.');
  end if;

  select pu.full_name into v_name from public.portal_users pu
   where pu.auth_user_id = auth.uid() and pu.clinic_id = p_clinic_id limit 1;

  /* A watch has to belong to SOMEBODY. Without this the row below is a watch
   * on the clinic rather than on a person, and the statement after it has
   * nothing to scope by. */
  if p_patient_id is null and p_diagnosis_id is null then
    return jsonb_build_object('ok', false, 'error',
      'A check interval has to be set on a patient or on a visit.');
  end if;

  /* One order at a time, per PATIENT — and a walk-in is identified by their
   * visit, not by a patient row they do not have.
   *
   * This read `clinic_patient_id is not distinct from p_patient_id`, and
   * `is not distinct from` treats null as equal to null. A walk-in has no
   * patient row — the table's own comment says so — so p_patient_id is null in
   * the ordinary case, and that condition matched EVERY walk-in's watch in the
   * clinic. Reproduced: three watches, two of them walk-ins, one
   * start_vital_watch call with a null patient id, and both walk-ins' watches
   * were stopped.
   *
   * On a ward that means a "monitor her every fifteen minutes" order on a
   * deteriorating patient silently ends because somebody set an interval on a
   * different walk-in — and a countdown that has stopped looks exactly like a
   * countdown that was never set. */
  update public.vital_watch
     set stopped_at = now(), stopped_by = auth.uid()
   where clinic_id = p_clinic_id
     and stopped_at is null
     and (
       (p_patient_id is not null and clinic_patient_id = p_patient_id)
       or
       (p_patient_id is null and clinic_patient_id is null
          and diagnosis_id = p_diagnosis_id)
     );

  insert into public.vital_watch
    (clinic_id, clinic_patient_id, diagnosis_id, interval_minutes, reason,
     started_by, started_by_name)
  values (p_clinic_id, p_patient_id, p_diagnosis_id, p_interval_minutes,
          nullif(btrim(coalesce(p_reason, '')), ''), auth.uid(), v_name)
  returning id into v_id;

  return jsonb_build_object('ok', true, 'id', v_id);
end $$;

grant execute on function public.start_vital_watch(uuid, uuid, uuid, integer, text) to authenticated;

create or replace function public.stop_vital_watch(
  p_watch_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_clinic uuid;
begin
  select clinic_id into v_clinic from public.vital_watch where id = p_watch_id;
  if v_clinic is null then
    return jsonb_build_object('ok', false, 'error', 'No such watch.');
  end if;
  if not public.is_clinic_staff(v_clinic) then
    return jsonb_build_object('ok', false, 'error', 'Not your clinic.');
  end if;
  update public.vital_watch
     set stopped_at = coalesce(stopped_at, now()), stopped_by = auth.uid()
   where id = p_watch_id;
  return jsonb_build_object('ok', true);
end $$;

grant execute on function public.stop_vital_watch(uuid) to authenticated;

-- ── 8. Grants ───────────────────────────────────────────────────────
-- Supabase grants these by default; stated here so a self-hosted database
-- behaves the same. Note there is no delete grant on the readings: the
-- policies already forbid it, and this says the same thing twice on purpose.
grant select, insert on public.vital_logs  to authenticated;
grant select, insert on public.vital_notes to authenticated;
grant select, insert, update on public.vital_watch to authenticated;


-- ════════════════════════════════════════════════════════════════════════
--  DONE.
--
--  To check it worked, run this in the same SQL Editor. It should return
--  three rows, all saying "yes".
--
--    select 'clinician portal' as feature,
--           case when to_regclass('public.clinicians') is not null
--                then 'yes' else 'NO' end as installed
--    union all
--    select 'owner corrections',
--           case when to_regclass('public.clinic_record_edits') is not null
--                then 'yes' else 'NO' end
--    union all
--    select 'vital flowsheet',
--           case when to_regclass('public.vital_logs') is not null
--                then 'yes' else 'NO' end;
--
--  Then, in the app: open a patient's record and tap the heart-monitor icon
--  in the header. If the flowsheet opens and a reading saves, it is in.
-- ════════════════════════════════════════════════════════════════════════
