-- =========================================================================
-- CHUNK 2 of 4 — REFERENCE (sections and categories)
--
-- Essential Medicines & Health Supplies List for Uganda (EMHSLU 2023).
-- Run 20260823_emhslu_schema.sql FIRST, then these in order.
-- Safe to re-run: every insert is ON CONFLICT DO NOTHING.
-- =========================================================================

insert into public.emhslu_sections (code, title) values
  ('A', 'ESSENTIAL MEDICINES LIST 2023'),
  ('B', 'GENERAL HEALTH SUPPLIES'),
  ('C', 'SPECIALIST HEALTH SUPPLIES'),
  ('D', 'LABORATORY SUPPLIES')
on conflict (code) do update set title = excluded.title;

insert into public.emhslu_categories (id, section, number, title) values
  (1, 'A', '1', 'ANAESTHETICS'),
  (2, 'A', '1.1', 'General anaesthetics and oxygen'),
  (3, 'A', '1.1.1', 'Inhalational medicines'),
  (4, 'A', '1.1.2', 'Injectable medicines'),
  (5, 'A', '1.2', 'Local anaesthetics'),
  (6, 'A', '1.3', 'Preoperative and peri-operative medication'),
  (7, 'A', '2', 'MEDICINES FOR PAIN AND PALLIATIVECARE'),
  (8, 'A', '2.1', 'Non-opioids and non-steroidal anti-inflammatory drugs (NSAIDS)'),
  (9, 'A', '2.2', 'Opioid analgesics'),
  (10, 'A', '2.3', 'Medicines for other common symptoms in palliative care'),
  (11, 'A', '3', 'ANTI-ALLERGICS AND MEDICINES USED IN ANAPHYLAXIS'),
  (12, 'A', '4', 'ANTIDOTES AND OTHER SUBSTANCES USED IN POISONING'),
  (13, 'A', '4.1', 'Non-specific antidotes'),
  (14, 'A', '4.2', 'Specific antidotes'),
  (15, 'A', '5', 'ANTIEPILEPTICS/ANTICONVULSANTS'),
  (16, 'A', '6', 'ANTI INFECTIVE MEDICINES'),
  (17, 'A', '6.1', 'Anti helminthics'),
  (18, 'A', '6.1.1', 'Intestinal antihelminthics'),
  (19, 'A', '6.1.2', 'Antifilarials'),
  (20, 'A', '6.1.3', 'Anti schistosomals and other antitrematode medicines'),
  (21, 'A', '6.2', 'Antibacterials'),
  (22, 'A', '6.2.1', 'Beta-lactam medicines'),
  (23, 'A', '6.2.2', 'Other antibacterial medicines'),
  (24, 'A', '6.2.3', 'Anti leprosy medicines'),
  (25, 'A', '6.2.4', 'Anti tuberculosis medicines'),
  (26, 'A', '6.3', 'Antifungal medicines'),
  (27, 'A', '6.4', 'Antiviral medicines'),
  (28, 'A', '6.4.1', 'Anti-herpes medicines'),
  (29, 'A', '6.4.2', 'Antiretrovirals'),
  (30, 'A', '6.4.2.1', 'Nucleoside/ Nucleotide reverse transcriptase inhibitors'),
  (31, 'A', '6.4.2.2', 'Non-nucleoside reverse transcriptase inhibitors'),
  (32, 'A', '6.4.2.3', 'Protease inhibitors'),
  (33, 'A', '6.4.2.5', 'Integrase inhibitors'),
  (34, 'A', '6.4.3', 'Anti hepatitis medicines'),
  (35, 'A', '6.4.3.1', 'Medicines for HepatitisB'),
  (36, 'A', '6.4.3.1.1', 'Nucleoside / Nucleotide reverse transcriptase inhibitors'),
  (37, 'A', '6.4.4', 'Other antivirals'),
  (38, 'A', '6.4.4.1', 'Covid-19'),
  (39, 'A', '6.5', 'Antiprotozoal medicines'),
  (40, 'A', '6.5.1', 'Ant amoebic and anti-giardiasis medicines'),
  (41, 'A', '6.5.2', 'Anti-leishmaniasis medicines'),
  (42, 'A', '6.5.3', 'Antimalarial medicines'),
  (43, 'A', '6.5.3.1', 'For curative treatment'),
  (44, 'A', '6.5.3.2', 'For prophylaxis'),
  (45, 'A', '6.5.4', 'Anti-pneumocystosis and anti-toxoplasmosis medicines'),
  (46, 'A', '6.5.5', 'Anti-trypanosomal medicines (African trypanosomiasis)'),
  (47, 'A', '7', 'ANTIMIGRAINEMEDICINES'),
  (48, 'A', '7.1', 'For treatment of acute attacks'),
  (49, 'A', '7.2', 'For prophylaxis'),
  (50, 'A', '8', 'ANTINEOPLASTIC AND IMMUNOSUPPRESSIVE MEDICINES'),
  (51, 'A', '8.1', 'Immunosuppressive medicines'),
  (52, 'A', '8.2', 'Cytotoxic and adjuvant medicines'),
  (53, 'A', '8.3', 'Hormones andantihormones'),
  (54, 'A', '9', 'ANTI PARKINSONISM MEDICINES'),
  (55, 'A', '10', 'MEDICINES AFFECTING THE BLOOD'),
  (56, 'A', '10.1', 'Anti anaemia medicines'),
  (57, 'A', '10.2', 'Medicines affecting coagulation'),
  (58, 'A', '10.3', 'Other medicines for haemoglobinopathies'),
  (59, 'A', '11', 'BLOOD PRODUCTS OF HUMAN ORIGIN AND PLASMA SUBSTITUTES'),
  (60, 'A', '11.1', 'Blood and blood components'),
  (61, 'A', '11.1.1', 'Blood coagulation factors'),
  (62, 'A', '11.2', 'Plasma substitutes'),
  (63, 'A', '12', 'CARDIOVASCULARMEDICINES'),
  (64, 'A', '12.1', 'Antianginal medicines'),
  (65, 'A', '12.2', 'Antiarrhythmic medicines'),
  (66, 'A', '12.3', 'Antihypertensive medicines'),
  (67, 'A', '12.3.1', 'Medicines for management of hypoglycemia'),
  (68, 'A', '12.4', 'Medicines used in heart failure'),
  (69, 'A', '12.5', 'Antithrombotic medicines'),
  (70, 'A', '12.5.1', 'Anti-platelet medicines'),
  (71, 'A', '12.6', 'Lipid-lowering agents'),
  (72, 'A', '13', 'DERMATOLOGICAL MEDICINES (Topical)'),
  (73, 'A', '13.1', 'Antifungal medicines'),
  (74, 'A', '13.2', 'Anti-infective medicines'),
  (75, 'A', '13.3', 'Anti-inflammatory and antipruritic medicines'),
  (76, 'A', '13.4', 'Medicines affecting skin differentiation and proliferation'),
  (77, 'A', '13.5', 'Scabicides and pediculicides'),
  (78, 'A', '13.6', 'Medicines for tungiasis (Jiggers)'),
  (79, 'A', '13.7', 'medicines for skin care for albinoism'),
  (80, 'A', '14', 'DIAGNOSTICAGENTS'),
  (81, 'A', '14.1', 'Ophthalmic medicines'),
  (82, 'A', '14.2', 'Cervical cancer screening'),
  (83, 'A', '14.3', 'Radiocontrast media (only specialist treatment)'),
  (84, 'A', '15', 'DISINFECTANTS AND ANTISEPTICS'),
  (85, 'A', '15.1', 'Antiseptics'),
  (86, 'A', '15.2', 'Disinfectants'),
  (87, 'A', '16', 'DIURETICS'),
  (88, 'A', '17', 'GASTROINTESTINAL MEDICINES'),
  (89, 'A', '17.1', 'Antacids and antiulcer medicines'),
  (90, 'A', '17.2', 'Antiemetic medicines'),
  (91, 'A', '17.3', 'Anti-inflammatory and Antihaemorrhoids medicines'),
  (92, 'A', '17.4', 'Laxatives'),
  (93, 'A', '17.5', 'Medicines used in diarrhoea'),
  (94, 'A', '17.5.1', 'Oral rehydration'),
  (95, 'A', '17.5.2', 'Medicines for diarrhoea'),
  (96, 'A', '17.6', 'Antispasmodics'),
  (97, 'A', '18', 'HORMONES, OTHER ENDOCRINE MEDICINES AND CONTRACEPTIVES'),
  (98, 'A', '18.1', 'Adrenal hormones and synthetic substitutes'),
  (99, 'A', '18.2', 'Androgens'),
  (100, 'A', '18.3', 'Contraceptives'),
  (101, 'A', '18.3.1', 'Oral hormonal contraceptives'),
  (102, 'A', '18.3.2', 'Injectable hormonal contraceptives'),
  (103, 'A', '18.3.3', 'Intrauterine devices'),
  (104, 'A', '18.3.4', 'Barrier methods'),
  (105, 'A', '18.3.5', 'Implantable contraceptives'),
  (106, 'A', '18.3.6', 'Others'),
  (107, 'A', '18.3.7', 'Management of IUFD'),
  (108, 'A', '18.4', 'Oestrogens'),
  (109, 'A', '18.5', 'Insulins and medicines used for diabetes'),
  (110, 'A', '18.5.1', 'Medicines for diabetic ketoacidosis'),
  (111, 'A', '18.5.2', 'Medicines for management of hypoglycemia'),
  (112, 'A', '18.6', 'Ovulation inducers'),
  (113, 'A', '18.7', 'Progestogens'),
  (114, 'A', '18.8', 'Thyroid hormones and antithyroid medicines'),
  (115, 'A', '19', 'IMMUNOLOGICALS'),
  (116, 'A', '19.1', 'Diagnostic agents'),
  (117, 'A', '19.2', 'Sera and immunoglobulins'),
  (118, 'A', '19.3', 'Vaccines'),
  (119, 'A', '20', 'MUSCLE RELAXANTS (PERIPHERALLY-ACTING) AND CHOLINESTERASEINHIBITORS'),
  (120, 'A', '21', 'OPHTHALMOLOGICALPREPARATIONS'),
  (121, 'A', '21.1', 'Anti-infective agents'),
  (122, 'A', '21.2', 'Anti-infective and anti-inflammatory agents'),
  (123, 'A', '21.3', 'Anti-inflammatory medicines'),
  (124, 'A', '21.4', 'Antifungal medicines'),
  (125, 'A', '21.5', 'Antiviral medicines'),
  (126, 'A', '21.6', 'Local anaesthetics'),
  (127, 'A', '21.7', 'Miotics and antiglaucoma medicines'),
  (128, 'A', '21.8', 'Mydriatics'),
  (129, 'A', '21.9', 'Anti-metabolites'),
  (130, 'A', '21.10', 'Lubricants'),
  (131, 'A', '21.11', 'Astringents'),
  (132, 'A', '22', 'OXYTOCICS ANDANTI-OXYTOCICS'),
  (133, 'A', '22.1', 'Oxytocics'),
  (134, 'A', '22.2', 'Anti-oxytocics(tocolytics)'),
  (135, 'A', '23', 'PERITONEAL AND HAEMODIALYSIS SOLUTIONS'),
  (136, 'A', '24', 'MEDICINES FOR MENTAL AND BEHAVIORAL DISORDERS'),
  (137, 'A', '24.1', 'Medicines used in Schizophrenia and other psychotic disorders'),
  (138, 'A', '24.2', 'Medicines used in mood disorders'),
  (139, 'A', '24.2.1', 'Medicines used in depressive and or anxiety disorders'),
  (140, 'A', '24.2.2', 'Medicines used in bipolar disorders'),
  (141, 'A', '24.2.3', 'Medicines used in obsessive compulsive disorder'),
  (142, 'A', '24.3.1', 'Medicines for sleep wake disorders'),
  (143, 'A', '24.5', 'Anti-dementia medicines'),
  (144, 'A', '24.6', 'Tardive Dyskinesia and other extrapyramidal side effects'),
  (145, 'A', '24.7', 'Medicines used for disruptive, impulse control and conduct disorder'),
  (146, 'A', '25', 'MEDICINES ACTING ON THE RESPIRATORYTRACT'),
  (147, 'A', '25.1', 'Anti-asthmatic and medicines for chronic obstructive pulmonary disease'),
  (148, 'A', '25.2', 'Medicines for COPD - Antibiotics'),
  (149, 'A', '26', 'SOLUTIONS CORRECTING WATER, ELECTROLYTE AND ACID-BASEDISTURBANCES'),
  (150, 'A', '26.1', 'Oral'),
  (151, 'A', '26.2', 'Parenteral'),
  (152, 'A', '26.3', 'Miscellaneous'),
  (153, 'A', '27', 'VITAMINS AND MINERALS'),
  (154, 'A', '28', 'EAR, NOSE AND THROAT MEDICINES'),
  (155, 'A', '28.1', 'Ear preparations'),
  (156, 'A', '28.2', 'Nasal preparations'),
  (157, 'A', '28.3', 'Oropharyngeal preparations'),
  (158, 'A', '29', 'SPECIFIC MEDICINES FOR NEONATAL CARE'),
  (159, 'A', '29.1', 'Medicines administered to the neonate'),
  (160, 'A', '29.2', 'Medicines administered to the mother'),
  (161, 'A', '30', 'MEDICINES FOR DISEASES OFJOINTS'),
  (162, 'A', '30.2', 'Medicines used to treat gout'),
  (163, 'A', '31', 'MEDICINES FOR NEUROSURGICALUSE'),
  (164, 'A', '31.1', 'For cerebral metabolism/perfusion'),
  (165, 'A', '31.2', 'Medicines for Parkinson disease'),
  (166, 'A', '32', 'NUTRITION'),
  (167, 'A', '75', 'kCal + 0.9g protein per'),
  (168, 'A', '100', 'kCal + 2.9g protein per'),
  (169, 'B', '1', 'ADMINISTRATION SETS, CANNULAS, NEEDLES AND SYRINGES'),
  (170, 'B', '1.1', 'Administration sets'),
  (171, 'B', '1.1.1', 'Airway guedel'),
  (172, 'B', '1.1.2', 'Infusion sets/giving sets'),
  (173, 'B', '1.2', 'Cannulas'),
  (174, 'B', '1.3', 'Needles'),
  (175, 'B', '1.4', 'Syringes'),
  (176, 'B', '2', 'ANTISEPTICS, DETERGENTS AND DISINFECTANTS'),
  (177, 'B', '3', 'BANDAGES ANDDRESSINGS'),
  (178, 'B', '3.1', 'Bandage dressings'),
  (179, 'B', '3.2', 'Cotton wool'),
  (180, 'B', '3.3', 'Gauze dressings'),
  (181, 'B', '3.4', 'PoP and Undercast dressings'),
  (182, 'B', '3.5', 'Tape adhesive'),
  (183, 'B', '3.6', 'Traction kits'),
  (184, 'B', '3.7', 'Wound dressings'),
  (185, 'B', '4', 'CATHETERS AND TUBES'),
  (186, 'B', '4.1', 'Catheters'),
  (187, 'B', '4.1.1', 'Condom/ penile catheter'),
  (188, 'B', '4.1.2', 'Catheter, urethral foley, 2-way'),
  (189, 'B', '4.1.3', 'Catheter, foley, 3-way, funnel & valve, 300mm'),
  (190, 'B', '4.1.4', 'Catheter, nelaton for urethral use, funnel 2-eye'),
  (191, 'B', '4.1.5', 'Catheter suction, lateral eye, funnel + control valve'),
  (192, 'B', '4.1.6', 'Catheter, stopper'),
  (193, 'B', '4.2', 'Tubes'),
  (194, 'B', '4.2.1', 'Tubes, endotracheal, plastic non-cuffed'),
  (195, 'B', '4.2.2', 'Tubes, endotracheal, plastic, cuffed'),
  (196, 'B', '4.2.3', 'Tube, feeding, infants'),
  (197, 'B', '4.2.4', 'Tube, stomach/feeding, Ryle/Levin (intra-nasal), graduated tip, metal tip4-holes'),
  (198, 'B', '4.2.5', 'Tube, rectal'),
  (199, 'B', '4.2.6', 'Tube, tracheostomy'),
  (200, 'B', '4.2.7', 'Tube, thorax drainage'),
  (201, 'B', '5', 'GLOVES'),
  (202, 'B', '5.1', 'Examination gloves'),
  (203, 'B', '5.2', 'Surgical gloves'),
  (204, 'B', '5.3', 'Other Gloves'),
  (205, 'B', '6', 'LIGATURES, SUTURE MATERIALS AND SURGICALS'),
  (206, 'B', '6.1', 'Sutures'),
  (207, 'B', '6.1.1', 'Nylon suture'),
  (208, 'B', '6.1.2', 'Polyglycolic acid (PGA) suture'),
  (209, 'B', '6.1.3', 'Silk suture'),
  (210, 'B', '56', 'EMHSLU: SECTION B: GENERAL HEALTH SUPPLIES'),
  (211, 'B', '6.2', 'Haemostats and Colostomy Bags'),
  (212, 'B', '7', 'PROTECTIVES'),
  (213, 'B', '7.1', 'Aprons'),
  (214, 'B', '7.2', 'Bins, waste'),
  (215, 'B', '7.3', 'Bin liners/ Bioharzard bags'),
  (216, 'B', '7.4', 'Boots and clogs'),
  (217, 'B', '7.5', 'Caps, masks and other clothing'),
  (218, 'B', '7.5.1', 'Covid 19 protective gear'),
  (219, 'B', '7.6', 'Safety box'),
  (220, 'B', '8', 'SURGICAL INSTRUMENTS'),
  (221, 'B', '8.1', 'Forceps'),
  (222, 'B', '8.1.1', 'Artery: straight & curved / tooth &non-tooth'),
  (223, 'B', '8.1.2', 'Dissecting: straight & curved / tooth & non-tooth'),
  (224, 'B', '8.1.3', 'For sponge handling, tissue grasping'),
  (225, 'B', '8.1.4', 'Other general forceps'),
  (226, 'B', '8.2', 'Needle holders'),
  (227, 'B', '8.3', 'Needles- special biopsy & spinal'),
  (228, 'B', '8.4', 'Obstetrics & Gynaecology supplies'),
  (229, 'B', '8.4.1', 'Forceps'),
  (230, 'B', '8.4.2', 'Speculums'),
  (231, 'B', '8.4.3', 'Delivery supplies'),
  (232, 'B', '8.5', 'Laryngoscopes'),
  (233, 'B', '8.6', 'Retractors'),
  (234, 'B', '8.7', 'Scissors for surgical use'),
  (235, 'B', '8.8', 'Surgical scalpel blades and handles'),
  (236, 'B', '8.9', 'Other surgical instruments'),
  (237, 'B', '8.10', 'Circumcision and Pap Smear Kits'),
  (238, 'B', '9', 'WARD AND THEATRE SUPPLIESAND ACCESSSORIES'),
  (239, 'B', '9.1', 'Equipment and accessories'),
  (240, 'B', '9.2', 'Hollow-ware, stainless steel or autoclavable polypropylene'),
  (241, 'B', '9.3', 'Masks and theatre accessories'),
  (242, 'B', '9.4', 'Nursing items'),
  (243, 'B', '9.5', 'Sterilisation bags'),
  (244, 'B', '9.6', 'Newborn care Items'),
  (245, 'B', '10', 'PACKINGBAGS'),
  (246, 'B', '11', 'RADIOLOGY AND OTHER IMAGING SUPPLIES'),
  (247, 'B', '12', 'STATIONERY AND STOCK MANAGEMENT'),
  (248, 'C', '1', 'LIGATURES AND SUTURE MATERIALS AND SURGICALS'),
  (249, 'C', '2', 'CATHETERS ANDTUBES'),
  (250, 'C', '2.1', 'Catheters'),
  (251, 'C', '2.2', 'Tubes'),
  (252, 'C', '2.3', 'Others'),
  (253, 'C', '3', 'ORTHOPAEDICSUPPLIES'),
  (254, 'C', '3.1', 'Drill bits'),
  (255, 'C', '3.2', 'Fixators'),
  (256, 'C', '3.3', 'Ilizarov system'),
  (257, 'C', '3.4', 'Nails'),
  (258, 'C', '3.5', 'Pins'),
  (259, 'C', '3.6', 'Plates'),
  (260, 'C', '3.7', 'Prostheses'),
  (261, 'C', '3.8', 'Screws'),
  (262, 'C', '3.8.1', 'Cancellous screws'),
  (263, 'C', '3.8.2', 'Cortical compression screws'),
  (264, 'C', '3.8.3', 'Dynamic hip screws (DHS)'),
  (265, 'C', '3.9', 'Wires'),
  (266, 'C', '3.10', 'Other Orthopaedic Supplies'),
  (267, 'C', '4', 'DIALYSIS SUPPLIES'),
  (268, 'C', '4.1', 'Haemodialysis'),
  (269, 'C', '4.2', 'Peritoneal dialysis'),
  (270, 'C', '5', 'DENTAL SUPPLIES'),
  (271, 'C', '5.1', 'Elevators'),
  (272, 'C', '5.2', 'Forceps'),
  (273, 'C', '5.3', 'Other dental instruments'),
  (274, 'C', '5.4', 'Syringes and needles'),
  (275, 'C', '5.5', 'Fillings and accessories'),
  (276, 'C', '5.6', 'Dental X-ray Supplies'),
  (277, 'C', '6', 'OPHTHALMICSUPPLIES'),
  (278, 'C', '7', 'PROTECTIVES'),
  (279, 'C', '8', 'BONE MARROW SUPPLIES'),
  (280, 'D', '82', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (281, 'D', '84', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (282, 'D', '86', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (283, 'D', '88', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (284, 'D', '90', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (285, 'D', '300', 'Per Box'),
  (286, 'D', '92', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (287, 'D', '94', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (288, 'D', '96', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (289, 'D', '98', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (290, 'D', '1', 'Pack x 12 PC'),
  (291, 'D', '100', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (292, 'D', '102', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (293, 'D', '104', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (294, 'D', '106', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (295, 'D', '108', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (296, 'D', '110', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (297, 'D', '112', 'EMHSLU: SECTION D: LABORATORY SUPPLIES'),
  (298, 'D', '2', 'National Standard Test Menu, Techniques and Supplies List for Laboratories, 2017'),
  (299, 'D', '3', 'Ministry of Health Uganda, 2023. Uganda Clinical Guidelines 2023'),
  (300, 'D', '4', 'World Health Organisation, 2021. 22ndWHO Model List of Essential Medicines, 2021'),
  (301, 'D', '114', 'EMHSLU'),
  (302, 'D', '116', 'EMHSLU'),
  (303, 'D', '118', 'EMHSLU: SECTION A: ESSENTIAL MEDICINES LIST 2023')
on conflict (id) do update set section = excluded.section, number = excluded.number, title = excluded.title;

-- 303 categories
